back_substitute – ParaMADP
back_substitute Subroutine
MIT
11 statements
Source File
public subroutine back_substitute(H, beta, k)
Apply BACK SUBSTITUTION
Arguments
Type Intent Optional Attributes Name
complex(kind=realdp), intent(in), dimension(m_iter+1,m_iter) :: H
complex(kind=realdp), intent(inout), dimension(m_iter+1) :: beta
integer, intent(in) :: k
Called by
Call graph
full_pgmres calls back_substitute
fullgmres calls back_substitute
pfgmres calls back_substitute
pre_fullgmres calls back_substitute
pre_restartgmres calls back_substitute
restartgmres calls back_substitute
helmholtz_2d calls full_pgmres, fullgmres, pfgmres, pre_fullgmres, pre_restartgmres, restartgmres