check_x2d – ParaMADP
check_x2d Subroutine
MIT
57 statements
Source File
public subroutine check_x2d(f)
Exchanges data in the x direction, ONLY for the default (finest) grid system
Arguments
Type Intent Optional Attributes Name
complex(kind=realdp) :: f(1-LAP:nx+LAP,1-LAP:ny+LAP)
Calls
Called by
Call graph
check_x2d calls mpi_sendrecv
check_xy2d calls check_x2d
helmholtz2d_bc calls check_xy2d
arnoldi calls helmholtz2d_bc
cmatvec calls helmholtz2d_bc
full_pgcr calls helmholtz2d_bc
full_pgmres calls helmholtz2d_bc
fullgmres calls helmholtz2d_bc, arnoldi
pfgmres calls helmholtz2d_bc
pre_fullgmres calls helmholtz2d_bc, prearnoldi
pre_restartgmres calls helmholtz2d_bc, prearnoldi
prearnoldi calls helmholtz2d_bc
restartgmres calls helmholtz2d_bc, arnoldi
operator(ASTERISK) calls cmatvec
helmholtz_2d calls full_pgcr, full_pgmres, fullgmres, pfgmres, pre_fullgmres, pre_restartgmres, restartgmres