Const_K – ParaMADP
Const_K Subroutine
MIT
11 statements
Source File
public subroutine Const_K()
constant wavenumber, determine by input variable k0 data communication with neighbouring subdomains
Arguments
None
Calls
Called by
Call graph
const_k calls mg_checkreal_xy2d
mg_checkreal_xy2d calls mg_checkreal_x2d, mg_checkreal_y2d
mg_checkreal_x2d calls mpi_sendrecv
mg_checkreal_y2d calls mpi_sendrecv
helmholtz_2d calls const_k