CSLP_Mx_nth – ParaMADP
CSLP_Mx_nth Function
MIT
72 statements
Source File
public function CSLP_Mx_nth(v_in, grid)
ReD-Glk CSLP operator for coarse levels
Arguments
Type Intent Optional Attributes Name
complex(kind=realdp), intent(inout) :: v_in(1-LAP:grid%nx+LAP,1-LAP:grid%ny+LAP)
type(Gridpara), intent(inout) :: grid
Return Value complex(kind=realdp), (1-LAP:grid%nx+LAP,1-LAP:grid%ny+LAP)
Calls
Called by
Call graph
cslp_mx_nth calls cslp2d_stencils, cslp_mx_nth_stencils, gridbase_extrpltghostbcs, log2, mg_check_xy2d
cslp_mx_nth_stencils calls log2
mg_check_xy2d calls mg_check_x2d, mg_check_y2d
mg_check_x2d calls mpi_sendrecv
mg_check_y2d calls mpi_sendrecv
red_glk_cslp_bicgstab calls cslp_mx_nth
red_glk_cslp_gmres calls cslp_mx_nth
krylovcslp_invmhx calls red_glk_cslp_gmres
def_prefgmres calls krylovcslp_invmhx, multileveladp_px
multileveladp_px calls krylovcslp_invmhx, multilevel_invey
def_px calls multileveladp_px
multilevel_invey calls def_prefgmres
precond_x calls def_px
full_pgcr calls precond_x
full_pgmres calls precond_x
pfgmres calls precond_x
pre_fullgmres calls precond_x, prearnoldi
pre_restartgmres calls precond_x, prearnoldi
prearnoldi calls precond_x
helmholtz_2d calls full_pgcr, full_pgmres, pfgmres, pre_fullgmres, pre_restartgmres