CSLP_OP_BC – ParaMADP
CSLP_OP_BC Subroutine
MIT
59 statements
Source File
public subroutine CSLP_OP_BC(v_in, v_out, ni, nj, hx_c, hy_c, kxy, kh2)
matrix-free CSLP operator, for the specified gird systems
Arguments
Type Intent Optional Attributes Name
complex(kind=realdp), intent(inout), dimension(1-LAP:ni+LAP,1-LAP:nj+LAP) :: v_in
complex(kind=realdp), intent(inout), dimension(1-LAP:ni+LAP,1-LAP:nj+LAP) :: v_out
integer, intent(in) :: ni
ni,nj: grid size of subdomain on the current grid level
integer, intent(in) :: nj
ni,nj: grid size of subdomain on the current grid level
real(kind=realdp), intent(in) :: hx_c
hx_c,hy_c: space step of subdomain on the current grid level
real(kind=realdp), intent(in) :: hy_c
hx_c,hy_c: space step of subdomain on the current grid level
real(kind=realdp), intent(in), dimension(1-LAP:ni+LAP,1-LAP:nj+LAP) :: kxy
kxy: wavenumber profile of subdomain on the current grid level,kh2=(kh)^2
real(kind=realdp), intent(in), dimension(1-LAP:ni+LAP,1-LAP:nj+LAP) :: kh2
kxy: wavenumber profile of subdomain on the current grid level,kh2=(kh)^2
Calls
Called by
Call graph
cslp_op_bc calls cslp2d_stencils, if_bcs, mg_check_xy2d
if_bcs calls dirichlet, first_order_neum
mg_check_xy2d calls mg_check_x2d, mg_check_y2d
mg_check_x2d calls mpi_sendrecv
mg_check_y2d calls mpi_sendrecv
f_cycle calls cslp_op_bc, f_cycle, mg_bicgstab, mg_fullgmres, v_cycle
mg_arnoldi calls cslp_op_bc
mg_bicgstab calls cslp_op_bc
mg_fullgmres calls cslp_op_bc, mg_arnoldi
v_cycle calls cslp_op_bc, mg_bicgstab, mg_fullgmres, v_cycle
mgcslp_invmhx calls f_cycle, v_cycle
mgcslp_invmx calls f_cycle, v_cycle
cprecon calls mgcslp_invmx
def_arnoldi calls mgcslp_invmhx, ex
def_bicgstab calls mgcslp_invmhx, ex
def_fullgmres calls mgcslp_invmhx, def_arnoldi, ex
ex calls mgcslp_invmhx
multileveladp_px calls mgcslp_invmhx, multilevel_invey
p_adef1x calls mgcslp_invmx, qx
p_tlkmx calls mgcslp_invmx, qx
precond_x calls mgcslp_invmx, def_px
operator(SLASH) calls cprecon
def_prefgmres calls multileveladp_px
def_px calls multileveladp_px, p_adef1x, p_tlkmx, p_defx
full_pgcr calls precond_x
full_pgmres calls precond_x
invey calls def_bicgstab, def_fullgmres
pfgmres calls precond_x
pre_fullgmres calls precond_x, prearnoldi
pre_restartgmres calls precond_x, prearnoldi
prearnoldi calls precond_x
multilevel_invey calls def_prefgmres
qx calls invey
helmholtz_2d calls full_pgcr, full_pgmres, pfgmres, pre_fullgmres, pre_restartgmres
p_defx calls qx
px calls qx