def_apply_givens_rotation – ParaMADP
def_apply_givens_rotation Subroutine
MIT
23 statements
Source File
public subroutine def_apply_givens_rotation(H, cs, sn, k)
Apply givens rotation of DEF_fullgmres
Arguments
Type Intent Optional Attributes Name
complex(kind=realdp), intent(inout), dimension(def_mg_miter+1,def_mg_miter) :: H
complex(kind=realdp), intent(inout), dimension(def_mg_miter+1) :: cs
complex(kind=realdp), intent(inout), dimension(def_mg_miter+1) :: sn
integer, intent(in) :: k
Calls
Called by
Call graph
def_apply_givens_rotation calls cdsqrt
def_fullgmres calls def_apply_givens_rotation
invey calls def_fullgmres
qx calls invey
p_adef1x calls qx
p_defx calls qx
p_tlkmx calls qx
px calls qx
def_px calls p_adef1x, p_defx, p_tlkmx
precond_x calls def_px
full_pgcr calls precond_x
full_pgmres calls precond_x
pfgmres calls precond_x
pre_fullgmres calls precond_x, prearnoldi
pre_restartgmres calls precond_x, prearnoldi
prearnoldi calls precond_x
helmholtz_2d calls full_pgcr, full_pgmres, pfgmres, pre_fullgmres, pre_restartgmres