define_uniform_grid – ParaMADP
define_uniform_grid Subroutine
MIT
58 statements
Source File
public subroutine define_uniform_grid(phys1, phys2)
A square computational domain with a unit side length
Arguments
Type Intent Optional Attributes Name
real(kind=realdp), dimension(1-LAP:nx+LAP,1-LAP:ny+LAP) :: phys1
Local coordinates in x and y directions
real(kind=realdp), dimension(1-LAP:nx+LAP,1-LAP:ny+LAP) :: phys2
Local coordinates in x and y directions
Calls
Called by
Call graph
define_uniform_grid calls mpi_recv, mpi_send
helmholtz_2d calls define_uniform_grid