finestgrid_define – ParaMADP
finestgrid_define Subroutine
MIT
25 statements
Source File
public subroutine finestgrid_define(mg_finest)
This is a routine that define the finest grid system from the default (finest) grid parameters
Arguments
Type Intent Optional Attributes Name
type(GridSystem), intent(inout) :: mg_finest
Called by
Call graph
mgcslp_invmx calls finestgrid_define
cprecon calls mgcslp_invmx
p_adef1x calls mgcslp_invmx
p_tlkmx calls mgcslp_invmx
precond_x calls mgcslp_invmx, def_px
operator(SLASH) calls cprecon
def_px calls p_adef1x, p_tlkmx
full_pgcr calls precond_x
full_pgmres calls precond_x
pfgmres calls precond_x
pre_fullgmres calls precond_x, prearnoldi
pre_restartgmres calls precond_x, prearnoldi
prearnoldi calls precond_x
helmholtz_2d calls full_pgcr, full_pgmres, pfgmres, pre_fullgmres, pre_restartgmres