FromFine2Coarse – ParaMADP
FromFine2Coarse Function
MIT
91 statements
Source File
public function FromFine2Coarse(OneGrid)
A procedure to create a two-grid system from a given fine Gridpara type The wavenumber of the coarse level is restricted from the fine level
Arguments
Type Intent Optional Attributes Name
type(Gridpara), intent(inout) :: OneGrid
Return Value type(TwoGrids)
Calls
Called by
Call graph
fromfine2coarse calls wavenumber_fwrestriction
wavenumber_fwrestriction calls mg_checkreal_xy2d
mg_checkreal_xy2d calls mg_checkreal_x2d, mg_checkreal_y2d
mg_checkreal_x2d calls mpi_sendrecv
mg_checkreal_y2d calls mpi_sendrecv
twogrids calls fromfine2coarse