GridBase_ExtrpltGhostBCs – ParaMADP
GridBase_ExtrpltGhostBCs Subroutine
MIT
108 statements
Source File
public subroutine GridBase_ExtrpltGhostBCs(v_in, grid)
Extrapolation of a layer of ghost grid points
Arguments
Type Intent Optional Attributes Name
complex(kind=realdp), intent(inout) :: v_in(1-LAP:grid%nx+LAP,1-LAP:grid%ny+LAP)
type(Gridpara), intent(inout) :: grid
Called by
Call graph
cslp_mx_nth calls gridbase_extrpltghostbcs
helm_ax_nth calls gridbase_extrpltghostbcs
def_prefgmres calls helm_ax_nth, multileveladp_px, krylovcslp_invmhx
multileveladp_px calls helm_ax_nth, krylovcslp_invmhx, multilevel_invey
red_glk_cslp_bicgstab calls cslp_mx_nth
red_glk_cslp_gmres calls cslp_mx_nth
def_px calls multileveladp_px
krylovcslp_invmhx calls red_glk_cslp_gmres
multilevel_invey calls def_prefgmres
precond_x calls def_px
full_pgcr calls precond_x
full_pgmres calls precond_x
pfgmres calls precond_x
pre_fullgmres calls precond_x, prearnoldi
pre_restartgmres calls precond_x, prearnoldi
prearnoldi calls precond_x
helmholtz_2d calls full_pgcr, full_pgmres, pfgmres, pre_fullgmres, pre_restartgmres