grid_destroy – ParaMADP
grid_destroy Subroutine
MIT
5 statements
Source File
public subroutine grid_destroy(mg_dm)
This is a routine that deallocate the arrays of a grid system
Arguments
Type Intent Optional Attributes Name
type(GridSystem), intent(inout) :: mg_dm
Called by
Call graph
f_cycle calls grid_destroy, f_cycle, v_cycle
krylovcslp_invmhx calls grid_destroy
mgcslp_invmhx calls grid_destroy, f_cycle, v_cycle
mgcslp_invmx calls grid_destroy, f_cycle, v_cycle
v_cycle calls grid_destroy, v_cycle
cprecon calls mgcslp_invmx
def_arnoldi calls mgcslp_invmhx, ex
def_bicgstab calls mgcslp_invmhx, ex
def_fullgmres calls mgcslp_invmhx, def_arnoldi, ex
def_prefgmres calls krylovcslp_invmhx, multileveladp_px
ex calls mgcslp_invmhx
multileveladp_px calls krylovcslp_invmhx, mgcslp_invmhx, multilevel_invey
p_adef1x calls mgcslp_invmx, qx
p_tlkmx calls mgcslp_invmx, qx
precond_x calls mgcslp_invmx, def_px
operator(SLASH) calls cprecon
def_px calls multileveladp_px, p_adef1x, p_tlkmx, p_defx
full_pgcr calls precond_x
full_pgmres calls precond_x
invey calls def_bicgstab, def_fullgmres
multilevel_invey calls def_prefgmres
pfgmres calls precond_x
pre_fullgmres calls precond_x, prearnoldi
pre_restartgmres calls precond_x, prearnoldi
prearnoldi calls precond_x
qx calls invey
helmholtz_2d calls full_pgcr, full_pgmres, pfgmres, pre_fullgmres, pre_restartgmres
p_defx calls qx
px calls qx