Helm_A2hx – ParaMADP
Helm_A2hx Function
MIT
18 statements
Source File
public function Helm_A2hx(x, f2c)
A function that performs the Helmholtz operator on the coarse grid of the two-grid system, by different methods ReD-O2 ReD-Glk ReD-cmpO4
Arguments
Type Intent Optional Attributes Name
complex(kind=realdp), intent(inout) :: x(1-LAP:f2c%nxc+LAP,1-LAP:f2c%nyc+LAP)
type(TwoGrids), intent(inout) :: f2c
Return Value complex(kind=realdp), (1-LAP:f2c%nxc+LAP,1-LAP:f2c%nyc+LAP)
Calls
Called by
Call graph
helm_a2hx calls helmholtz2d_bc_mg, helmholtz2d_o4cmpct, helmholtz2d_red_glk
helmholtz2d_bc_mg calls helmholtz2d_stencils, if_bcs, mg_check_xy2d
helmholtz2d_o4cmpct calls mg_check_xy2d
helmholtz2d_red_glk calls extrpltghostbcs, helmholtz2d_stencils, mg_check_xy2d, red_glk_stencils
if_bcs calls dirichlet, first_order_neum
mg_check_xy2d calls mg_check_x2d, mg_check_y2d
mg_check_x2d calls mpi_sendrecv
mg_check_y2d calls mpi_sendrecv
ex calls helm_a2hx
def_arnoldi calls ex
def_bicgstab calls ex
def_fullgmres calls ex, def_arnoldi
invey calls def_bicgstab, def_fullgmres
qx calls invey
p_adef1x calls qx
p_defx calls qx
p_tlkmx calls qx
px calls qx
def_px calls p_adef1x, p_defx, p_tlkmx
precond_x calls def_px
full_pgcr calls precond_x
full_pgmres calls precond_x
pfgmres calls precond_x
pre_fullgmres calls precond_x, prearnoldi
pre_restartgmres calls precond_x, prearnoldi
prearnoldi calls precond_x
helmholtz_2d calls full_pgcr, full_pgmres, pfgmres, pre_fullgmres, pre_restartgmres