Helm_Ax_nth – ParaMADP
Helm_Ax_nth Function
MIT
72 statements
Source File
public function Helm_Ax_nth(v_in, grid)
ReD-Glk Helmholtz operator for coarse levels
Arguments
Type Intent Optional Attributes Name
complex(kind=realdp), intent(inout) :: v_in(1-LAP:grid%nx+LAP,1-LAP:grid%ny+LAP)
type(Gridpara), intent(inout) :: grid
Parameters of the current grid system
Return Value complex(kind=realdp), (1-LAP:grid%nx+LAP,1-LAP:grid%ny+LAP)
Calls
Called by
Call graph
helm_ax_nth calls gridbase_extrpltghostbcs, helm_ax_nth_stencils, helmholtz2d_stencils, log2, mg_check_xy2d
helm_ax_nth_stencils calls log2
mg_check_xy2d calls mg_check_x2d, mg_check_y2d
mg_check_x2d calls mpi_sendrecv
mg_check_y2d calls mpi_sendrecv
def_prefgmres calls helm_ax_nth, multileveladp_px
multileveladp_px calls helm_ax_nth, multilevel_invey
def_px calls multileveladp_px
multilevel_invey calls def_prefgmres
precond_x calls def_px
full_pgcr calls precond_x
full_pgmres calls precond_x
pfgmres calls precond_x
pre_fullgmres calls precond_x, prearnoldi
pre_restartgmres calls precond_x, prearnoldi
prearnoldi calls precond_x
helmholtz_2d calls full_pgcr, full_pgmres, pfgmres, pre_fullgmres, pre_restartgmres