Helmholtz2d_BC_mg – ParaMADP
Helmholtz2d_BC_mg Subroutine
MIT
59 statements
Source File
public subroutine Helmholtz2d_BC_mg(v_in, v_out, ni, nj, hx_c, hy_c, kxy, kh2)
matrix-free Helmholtz operator, for the specified coarse gird systems
Arguments
Type Intent Optional Attributes Name
complex(kind=realdp), intent(inout), dimension(1-LAP:ni+LAP,1-LAP:nj+LAP) :: v_in
complex(kind=realdp), intent(inout), dimension(1-LAP:ni+LAP,1-LAP:nj+LAP) :: v_out
integer, intent(in) :: ni
integer, intent(in) :: nj
real(kind=realdp), intent(in) :: hx_c
real(kind=realdp), intent(in) :: hy_c
real(kind=realdp), intent(in), dimension(1-LAP:ni+LAP,1-LAP:nj+LAP) :: kxy
real(kind=realdp), intent(in), dimension(1-LAP:ni+LAP,1-LAP:nj+LAP) :: kh2
Calls
Called by
Call graph
helmholtz2d_bc_mg calls helmholtz2d_stencils, if_bcs, mg_check_xy2d
if_bcs calls dirichlet, first_order_neum
mg_check_xy2d calls mg_check_x2d, mg_check_y2d
mg_check_x2d calls mpi_sendrecv
mg_check_y2d calls mpi_sendrecv
helm_a2hx calls helmholtz2d_bc_mg
helm_ahx calls helmholtz2d_bc_mg
ex calls helm_a2hx, helm_ahx
p_adef1x calls helm_ahx, qx
p_defx calls helm_ahx, qx
p_tlkmx calls helm_ahx, qx
px calls helm_ahx, qx
def_arnoldi calls ex
def_bicgstab calls ex
def_fullgmres calls ex, def_arnoldi
def_px calls p_adef1x, p_defx, p_tlkmx
invey calls def_bicgstab, def_fullgmres
precond_x calls def_px
full_pgcr calls precond_x
full_pgmres calls precond_x
pfgmres calls precond_x
pre_fullgmres calls precond_x, prearnoldi
pre_restartgmres calls precond_x, prearnoldi
prearnoldi calls precond_x
qx calls invey
helmholtz_2d calls full_pgcr, full_pgmres, pfgmres, pre_fullgmres, pre_restartgmres