Helmholtz2d_stencils – ParaMADP
Helmholtz2d_stencils Subroutine
MIT
11 statements
Source File
public subroutine Helmholtz2d_stencils(ap, an, as, aw, ae, hxhykxy2)
Computational stencils for the Helmholtz operator, second-order central FD scheme
Arguments
Type Intent Optional Attributes Name
complex(kind=realdp) :: ap
real(kind=realdp) :: an
real(kind=realdp) :: as
real(kind=realdp) :: aw
real(kind=realdp) :: ae
real(kind=realdp), intent(in) :: hxhykxy2
The value of (kh)^2, which is computed and stored in advance.
Called by
Call graph
helm_ax_nth calls helmholtz2d_stencils
helmholtz2d_bc calls helmholtz2d_stencils
helmholtz2d_bc_mg calls helmholtz2d_stencils
helmholtz2d_red_glk calls helmholtz2d_stencils
arnoldi calls helmholtz2d_bc
cmatvec calls helmholtz2d_bc
def_prefgmres calls helm_ax_nth, multileveladp_px
full_pgcr calls helmholtz2d_bc, precond_x
full_pgmres calls helmholtz2d_bc, precond_x
fullgmres calls helmholtz2d_bc, arnoldi
helm_a2hx calls helmholtz2d_bc_mg, helmholtz2d_red_glk
helm_ahx calls helmholtz2d_bc_mg
multileveladp_px calls helm_ax_nth, multilevel_invey
pfgmres calls helmholtz2d_bc, precond_x
pre_fullgmres calls helmholtz2d_bc, prearnoldi, precond_x
pre_restartgmres calls helmholtz2d_bc, prearnoldi, precond_x
prearnoldi calls helmholtz2d_bc, precond_x
restartgmres calls helmholtz2d_bc, arnoldi
operator(ASTERISK) calls cmatvec
def_px calls multileveladp_px, p_adef1x, p_defx, p_tlkmx
ex calls helm_a2hx, helm_ahx
multilevel_invey calls def_prefgmres
p_adef1x calls helm_ahx, qx
p_defx calls helm_ahx, qx
p_tlkmx calls helm_ahx, qx
px calls helm_ahx, qx
helmholtz_2d calls full_pgcr, full_pgmres, fullgmres, pfgmres, pre_fullgmres, pre_restartgmres, restartgmres
def_arnoldi calls ex
def_bicgstab calls ex
def_fullgmres calls ex, def_arnoldi
precond_x calls def_px
invey calls def_bicgstab, def_fullgmres
qx calls invey