LOG2 – ParaMADP
LOG2 Function
MIT
5 statements
Source File
public function LOG2(x)
Compute log2(x)
Arguments
Type Intent Optional Attributes Name
real(kind=realdp), intent(in) :: x
Return Value real(kind=realdp)
Called by
Call graph
cslp_mx_nth calls log2, cslp_mx_nth_stencils
cslp_mx_nth_stencils calls log2
helm_ax_nth calls log2, helm_ax_nth_stencils
helm_ax_nth_stencils calls log2
multilevel_invey calls log2, def_prefgmres
multileveladp_px calls log2, helm_ax_nth, multilevel_invey, krylovcslp_invmhx
red_glk_cslp_gmres calls log2, cslp_mx_nth
helmholtz_2d calls log2, full_pgcr, full_pgmres, pfgmres, pre_fullgmres, pre_restartgmres
def_prefgmres calls helm_ax_nth, multileveladp_px, krylovcslp_invmhx
def_px calls multileveladp_px
krylovcslp_invmhx calls red_glk_cslp_gmres
red_glk_cslp_bicgstab calls cslp_mx_nth
precond_x calls def_px
full_pgcr calls precond_x
full_pgmres calls precond_x
pfgmres calls precond_x
pre_fullgmres calls precond_x, prearnoldi
pre_restartgmres calls precond_x, prearnoldi
prearnoldi calls precond_x