mg_bicgstab – ParaMADP
mg_bicgstab Subroutine
MIT
78 statements
Source File
public subroutine mg_bicgstab(mg_solve, maximum_iterations)
This is a rountine to solve the (specified) coarsest-grid CSLP system approximately by using Bi-CGSTAB The CSLP is define by ReD-O2 scheme
Arguments
Type Intent Optional Attributes Name
type(GridSystem), intent(inout) :: mg_solve
integer, intent(in), optional :: maximum_iterations
User-specified maximum number of iterations
Calls
Called by
Call graph
mg_bicgstab calls cslp_op_bc, mg_dot_prod, mg_norm
cslp_op_bc calls cslp2d_stencils, if_bcs, mg_check_xy2d
mg_dot_prod calls mpi_allreduce
mg_norm calls mpi_allreduce
if_bcs calls dirichlet, first_order_neum
mg_check_xy2d calls mg_check_x2d, mg_check_y2d
mg_check_x2d calls mpi_sendrecv
mg_check_y2d calls mpi_sendrecv
f_cycle calls mg_bicgstab, f_cycle, v_cycle
v_cycle calls mg_bicgstab, v_cycle
mgcslp_invmhx calls f_cycle, v_cycle
mgcslp_invmx calls f_cycle, v_cycle
cprecon calls mgcslp_invmx
def_arnoldi calls mgcslp_invmhx, ex
def_bicgstab calls mgcslp_invmhx, ex
def_fullgmres calls mgcslp_invmhx, def_arnoldi, ex
ex calls mgcslp_invmhx
multileveladp_px calls mgcslp_invmhx, multilevel_invey
p_adef1x calls mgcslp_invmx, qx
p_tlkmx calls mgcslp_invmx, qx
precond_x calls mgcslp_invmx, def_px
operator(SLASH) calls cprecon
def_prefgmres calls multileveladp_px
def_px calls multileveladp_px, p_adef1x, p_tlkmx, p_defx
full_pgcr calls precond_x
full_pgmres calls precond_x
invey calls def_bicgstab, def_fullgmres
pfgmres calls precond_x
pre_fullgmres calls precond_x, prearnoldi
pre_restartgmres calls precond_x, prearnoldi
prearnoldi calls precond_x
multilevel_invey calls def_prefgmres
qx calls invey
helmholtz_2d calls full_pgcr, full_pgmres, pfgmres, pre_fullgmres, pre_restartgmres
p_defx calls qx
px calls qx