mg_check_xy2d – ParaMADP
mg_check_xy2d Subroutine
MIT
7 statements
Source File
public subroutine mg_check_xy2d(f, ni, nj)
Exchanges data first in the x direction and then y direction, for a specified-size grid system
Arguments
Type Intent Optional Attributes Name
complex(kind=realdp) :: f(1-LAP:ni+LAP,1-LAP:nj+LAP)
integer, intent(in) :: ni
integer, intent(in) :: nj
Calls
Called by
Call graph
mg_check_xy2d calls mg_check_x2d, mg_check_y2d
mg_check_x2d calls mpi_sendrecv
mg_check_y2d calls mpi_sendrecv
cslp_mx_nth calls mg_check_xy2d
cslp_op_bc calls mg_check_xy2d
damp_jacobi_smoother calls mg_check_xy2d
helm_ax_nth calls mg_check_xy2d
helmholtz2d_bc_mg calls mg_check_xy2d
helmholtz2d_o4cmpct calls mg_check_xy2d
helmholtz2d_red_glk calls mg_check_xy2d
prolongation_en_correct calls mg_check_xy2d
restriction calls mg_check_xy2d
ztx calls mg_check_xy2d
zx calls mg_check_xy2d
def_prefgmres calls helm_ax_nth, multileveladp_px, krylovcslp_invmhx
ex calls ztx, zx, helm_a2hx, helm_ahx, ztzx, mgcslp_invmhx
f_cycle calls cslp_op_bc, damp_jacobi_smoother, prolongation_en_correct, restriction, f_cycle, mg_bicgstab, mg_fullgmres, v_cycle
helm_a2hx calls helmholtz2d_bc_mg, helmholtz2d_o4cmpct, helmholtz2d_red_glk
helm_ahx calls helmholtz2d_bc_mg
mg_arnoldi calls cslp_op_bc
mg_bicgstab calls cslp_op_bc
mg_fullgmres calls cslp_op_bc, mg_arnoldi
multileveladp_px calls helm_ax_nth, ztx, zx, krylovcslp_invmhx, mgcslp_invmhx, multilevel_invey
qx calls ztx, zx, invey
red_glk_cslp_bicgstab calls cslp_mx_nth
red_glk_cslp_gmres calls cslp_mx_nth
v_cycle calls cslp_op_bc, damp_jacobi_smoother, prolongation_en_correct, restriction, mg_bicgstab, mg_fullgmres, v_cycle
ztzx calls ztx, zx
def_arnoldi calls ex, mgcslp_invmhx
def_bicgstab calls ex, mgcslp_invmhx
def_fullgmres calls ex, def_arnoldi, mgcslp_invmhx
def_px calls multileveladp_px, p_adef1x, p_defx, p_tlkmx
krylovcslp_invmhx calls red_glk_cslp_gmres
mgcslp_invmhx calls f_cycle, v_cycle
mgcslp_invmx calls f_cycle, v_cycle
multilevel_invey calls def_prefgmres
p_adef1x calls helm_ahx, qx, mgcslp_invmx
p_defx calls helm_ahx, qx
p_tlkmx calls helm_ahx, qx, mgcslp_invmx
px calls helm_ahx, qx
cprecon calls mgcslp_invmx
invey calls def_bicgstab, def_fullgmres
precond_x calls def_px, mgcslp_invmx
operator(SLASH) calls cprecon
full_pgcr calls precond_x
full_pgmres calls precond_x
pfgmres calls precond_x
pre_fullgmres calls precond_x, prearnoldi
pre_restartgmres calls precond_x, prearnoldi
prearnoldi calls precond_x
helmholtz_2d calls full_pgcr, full_pgmres, pfgmres, pre_fullgmres, pre_restartgmres