mg_checkreal_xy2d – ParaMADP
mg_checkreal_xy2d Subroutine
MIT
7 statements
Source File
public subroutine mg_checkreal_xy2d(f, ni, nj)
Exchanges REAL data first in the x direction and then y direction, for a specified-size grid system
Arguments
Type Intent Optional Attributes Name
real(kind=realdp) :: f(1-LAP:ni+LAP,1-LAP:nj+LAP)
integer, intent(in) :: ni
integer, intent(in) :: nj
Calls
Called by
Call graph
mg_checkreal_xy2d calls mg_checkreal_x2d, mg_checkreal_y2d
mg_checkreal_x2d calls mpi_sendrecv
mg_checkreal_y2d calls mpi_sendrecv
const_k calls mg_checkreal_xy2d
read_wavenumber_k_marmousi calls mg_checkreal_xy2d
restriction calls mg_checkreal_xy2d
wavenumber_fwrestriction calls mg_checkreal_xy2d
wavenumber_k_wedge calls mg_checkreal_xy2d
f_cycle calls restriction, f_cycle, v_cycle
fromfine2coarse calls wavenumber_fwrestriction
v_cycle calls restriction, v_cycle
helmholtz_2d calls const_k, read_wavenumber_k_marmousi, wavenumber_k_wedge, full_pgcr, full_pgmres, pfgmres, pre_fullgmres, pre_restartgmres
twogrids calls fromfine2coarse
mgcslp_invmhx calls f_cycle, v_cycle
mgcslp_invmx calls f_cycle, v_cycle
cprecon calls mgcslp_invmx
def_arnoldi calls mgcslp_invmhx, ex
def_bicgstab calls mgcslp_invmhx, ex
def_fullgmres calls mgcslp_invmhx, def_arnoldi, ex
ex calls mgcslp_invmhx
multileveladp_px calls mgcslp_invmhx, multilevel_invey
p_adef1x calls mgcslp_invmx, qx
p_tlkmx calls mgcslp_invmx, qx
precond_x calls mgcslp_invmx, def_px
operator(SLASH) calls cprecon
def_prefgmres calls multileveladp_px
def_px calls multileveladp_px, p_adef1x, p_tlkmx, p_defx
full_pgcr calls precond_x
full_pgmres calls precond_x
invey calls def_bicgstab, def_fullgmres
pfgmres calls precond_x
pre_fullgmres calls precond_x, prearnoldi
pre_restartgmres calls precond_x, prearnoldi
prearnoldi calls precond_x
multilevel_invey calls def_prefgmres
qx calls invey
p_defx calls qx
px calls qx