MGCSLP_invMHx – ParaMADP
MGCSLP_invMHx Function
MIT
30 statements
Source File
public function MGCSLP_invMHx(b_in, grid)
Multigrid-based CSLP, starts from the a specified grid system One V-cycle Two V-cycle One F-cycle
Arguments
Type Intent Optional Attributes Name
complex(kind=realdp), dimension(1-LAP:grid%nx+LAP,1-LAP:grid%ny+LAP) :: b_in
type(Gridpara) :: grid
A data type that collect some parameters of a system
Return Value complex(kind=realdp), dimension(1-LAP:grid%nx+LAP,1-LAP:grid%ny+LAP)
MGCSLP_invMHx = M_H^(-1)(b_H)
Calls
Called by
Call graph
mgcslp_invmhx calls f_cycle, grid_destroy, gridsys_define, v_cycle
f_cycle calls f_cycle, grid_destroy, v_cycle, coarsegrid_create, cslp_op_bc, damp_jacobi_smoother, mg_bicgstab, mg_fullgmres, prolongation_en_correct, restriction
v_cycle calls grid_destroy, v_cycle, coarsegrid_create, cslp_op_bc, damp_jacobi_smoother, mg_bicgstab, mg_fullgmres, prolongation_en_correct, restriction
cslp_op_bc calls cslp2d_stencils, if_bcs, mg_check_xy2d
damp_jacobi_smoother calls cslp2d_stencils, if_bcs, mg_check_xy2d
mg_bicgstab calls cslp_op_bc, mg_dot_prod, mg_norm
mg_fullgmres calls cslp_op_bc, mg_apply_givens_rotation, mg_arnoldi, mg_back_substitute, mg_norm
prolongation_en_correct calls mg_check_xy2d
restriction calls mg_check_xy2d, mg_checkreal_xy2d
if_bcs calls dirichlet, first_order_neum
mg_apply_givens_rotation calls cdsqrt
mg_arnoldi calls cslp_op_bc, mg_dot_prod, mg_norm
mg_check_xy2d calls mg_check_x2d, mg_check_y2d
mg_checkreal_xy2d calls mg_checkreal_x2d, mg_checkreal_y2d
mg_dot_prod calls mpi_allreduce
mg_norm calls mpi_allreduce
mg_check_x2d calls mpi_sendrecv
mg_check_y2d calls mpi_sendrecv
mg_checkreal_x2d calls mpi_sendrecv
mg_checkreal_y2d calls mpi_sendrecv
def_arnoldi calls mgcslp_invmhx, ex
def_bicgstab calls mgcslp_invmhx, ex
def_fullgmres calls mgcslp_invmhx, def_arnoldi, ex
ex calls mgcslp_invmhx
multileveladp_px calls mgcslp_invmhx, multilevel_invey
def_prefgmres calls multileveladp_px
def_px calls multileveladp_px, p_adef1x, p_defx, p_tlkmx
invey calls def_bicgstab, def_fullgmres
multilevel_invey calls def_prefgmres
precond_x calls def_px
qx calls invey
full_pgcr calls precond_x
full_pgmres calls precond_x
p_adef1x calls qx
p_defx calls qx
p_tlkmx calls qx
pfgmres calls precond_x
pre_fullgmres calls precond_x, prearnoldi
pre_restartgmres calls precond_x, prearnoldi
prearnoldi calls precond_x
px calls qx
helmholtz_2d calls full_pgcr, full_pgmres, pfgmres, pre_fullgmres, pre_restartgmres