MGCSLP_invMx – ParaMADP
MGCSLP_invMx Function
MIT
29 statements
Source File
public function MGCSLP_invMx(b_in)
Multigrid-Based CSLP, ONLY starts from the default (finest) grid sysyem One V-cycle Two V-cycle One F-cycle
Arguments
Type Intent Optional Attributes Name
complex(kind=realdp), dimension(1-LAP:nx+LAP,1-LAP:ny+LAP) :: b_in
Return Value complex(kind=realdp), (1-LAP:nx+LAP,1-LAP:ny+LAP)
MGCSLP_invMx = M_h^(-1)(b_h)
Calls
Called by
Call graph
mgcslp_invmx calls f_cycle, finestgrid_define, grid_destroy, v_cycle
f_cycle calls f_cycle, grid_destroy, v_cycle, coarsegrid_create, cslp_op_bc, damp_jacobi_smoother, mg_bicgstab, mg_fullgmres, prolongation_en_correct, restriction
v_cycle calls grid_destroy, v_cycle, coarsegrid_create, cslp_op_bc, damp_jacobi_smoother, mg_bicgstab, mg_fullgmres, prolongation_en_correct, restriction
cslp_op_bc calls cslp2d_stencils, if_bcs, mg_check_xy2d
damp_jacobi_smoother calls cslp2d_stencils, if_bcs, mg_check_xy2d
mg_bicgstab calls cslp_op_bc, mg_dot_prod, mg_norm
mg_fullgmres calls cslp_op_bc, mg_apply_givens_rotation, mg_arnoldi, mg_back_substitute, mg_norm
prolongation_en_correct calls mg_check_xy2d
restriction calls mg_check_xy2d, mg_checkreal_xy2d
if_bcs calls dirichlet, first_order_neum
mg_apply_givens_rotation calls cdsqrt
mg_arnoldi calls cslp_op_bc, mg_dot_prod, mg_norm
mg_check_xy2d calls mg_check_x2d, mg_check_y2d
mg_checkreal_xy2d calls mg_checkreal_x2d, mg_checkreal_y2d
mg_dot_prod calls mpi_allreduce
mg_norm calls mpi_allreduce
mg_check_x2d calls mpi_sendrecv
mg_check_y2d calls mpi_sendrecv
mg_checkreal_x2d calls mpi_sendrecv
mg_checkreal_y2d calls mpi_sendrecv
cprecon calls mgcslp_invmx
p_adef1x calls mgcslp_invmx
p_tlkmx calls mgcslp_invmx
precond_x calls mgcslp_invmx, def_px
operator(SLASH) calls cprecon
def_px calls p_adef1x, p_tlkmx
full_pgcr calls precond_x
full_pgmres calls precond_x
pfgmres calls precond_x
pre_fullgmres calls precond_x, prearnoldi
pre_restartgmres calls precond_x, prearnoldi
prearnoldi calls precond_x
helmholtz_2d calls full_pgcr, full_pgmres, pfgmres, pre_fullgmres, pre_restartgmres