ReD_Glk_CSLP_gmres – ParaMADP
ReD_Glk_CSLP_gmres Subroutine
MIT
90 statements
Source File
public subroutine ReD_Glk_CSLP_gmres(mg_solve, grid, maximum_iterations)
This is a rountine to solve a coarse grid CSLP system approximately by using GMRES The CSLP operator is defined by ReD-Glk scheme CSLP operator by ReD-Glk
Be careful!!, after the whole iteration without achieving eps, then the value of j will be "m_iter+1".So we need a k.
Attention: h_(i,j)=(w,v_i)=v^H*w, for complex value, so the code should be dot_product(v_i,w) ---call back_substitute(H,beta,k)---------------------------------
Arguments
Type Intent Optional Attributes Name
type(GridSystem), intent(inout) :: mg_solve
type(Gridpara) :: grid
integer, intent(in), optional :: maximum_iterations
User-specified maximum number of iterations,default is 300
Calls
Called by
Call graph
red_glk_cslp_gmres calls cdsqrt, cslp_mx_nth, log2, mg_dot_prod, mg_norm
cslp_mx_nth calls log2, cslp2d_stencils, cslp_mx_nth_stencils, gridbase_extrpltghostbcs, mg_check_xy2d
mg_dot_prod calls mpi_allreduce
mg_norm calls mpi_allreduce
cslp_mx_nth_stencils calls log2
mg_check_xy2d calls mg_check_x2d, mg_check_y2d
mg_check_x2d calls mpi_sendrecv
mg_check_y2d calls mpi_sendrecv
krylovcslp_invmhx calls red_glk_cslp_gmres
def_prefgmres calls krylovcslp_invmhx, multileveladp_px
multileveladp_px calls krylovcslp_invmhx, multilevel_invey
def_px calls multileveladp_px
multilevel_invey calls def_prefgmres
precond_x calls def_px
full_pgcr calls precond_x
full_pgmres calls precond_x
pfgmres calls precond_x
pre_fullgmres calls precond_x, prearnoldi
pre_restartgmres calls precond_x, prearnoldi
prearnoldi calls precond_x
helmholtz_2d calls full_pgcr, full_pgmres, pfgmres, pre_fullgmres, pre_restartgmres