V_cycle – ParaMADP
V_cycle Subroutine
MIT
35 statements
Source File
public recursive subroutine V_cycle(mg_fine)
A classic multigrid V-cycle A classic Two-Cycle GMRES or Bi-CGSTAB can be chose to solve the coarse-grid problem GMRES or Bi-CGSTAB can be chose to solve the coarsest-grid problem
Arguments
Type Intent Optional Attributes Name
type(GridSystem), intent(inout) :: mg_fine
Calls
Called by
Call graph
v_cycle calls v_cycle, coarsegrid_create, cslp_op_bc, damp_jacobi_smoother, grid_destroy, mg_bicgstab, mg_fullgmres, prolongation_en_correct, restriction
cslp_op_bc calls cslp2d_stencils, if_bcs, mg_check_xy2d
damp_jacobi_smoother calls cslp2d_stencils, if_bcs, mg_check_xy2d
mg_bicgstab calls cslp_op_bc, mg_dot_prod, mg_norm
mg_fullgmres calls cslp_op_bc, mg_apply_givens_rotation, mg_arnoldi, mg_back_substitute, mg_norm
prolongation_en_correct calls mg_check_xy2d
restriction calls mg_check_xy2d, mg_checkreal_xy2d
if_bcs calls dirichlet, first_order_neum
mg_apply_givens_rotation calls cdsqrt
mg_arnoldi calls cslp_op_bc, mg_dot_prod, mg_norm
mg_check_xy2d calls mg_check_x2d, mg_check_y2d
mg_checkreal_xy2d calls mg_checkreal_x2d, mg_checkreal_y2d
mg_dot_prod calls mpi_allreduce
mg_norm calls mpi_allreduce
mg_check_x2d calls mpi_sendrecv
mg_check_y2d calls mpi_sendrecv
mg_checkreal_x2d calls mpi_sendrecv
mg_checkreal_y2d calls mpi_sendrecv
f_cycle calls v_cycle, f_cycle
mgcslp_invmhx calls v_cycle, f_cycle
mgcslp_invmx calls v_cycle, f_cycle
cprecon calls mgcslp_invmx
def_arnoldi calls mgcslp_invmhx, ex
def_bicgstab calls mgcslp_invmhx, ex
def_fullgmres calls mgcslp_invmhx, def_arnoldi, ex
ex calls mgcslp_invmhx
multileveladp_px calls mgcslp_invmhx, multilevel_invey
p_adef1x calls mgcslp_invmx, qx
p_tlkmx calls mgcslp_invmx, qx
precond_x calls mgcslp_invmx, def_px
operator(SLASH) calls cprecon
def_prefgmres calls multileveladp_px
def_px calls multileveladp_px, p_adef1x, p_tlkmx, p_defx
full_pgcr calls precond_x
full_pgmres calls precond_x
invey calls def_bicgstab, def_fullgmres
pfgmres calls precond_x
pre_fullgmres calls precond_x, prearnoldi
pre_restartgmres calls precond_x, prearnoldi
prearnoldi calls precond_x
multilevel_invey calls def_prefgmres
qx calls invey
helmholtz_2d calls full_pgcr, full_pgmres, pfgmres, pre_fullgmres, pre_restartgmres
p_defx calls qx
px calls qx