wavenumber_FWrestriction – ParaMADP
wavenumber_FWrestriction Subroutine
MIT
44 statements
Source File
public subroutine wavenumber_FWrestriction(f2c)
This routine obtains the wavenumber of the coarse level by full-weight restriction from the fine level
Arguments
Type Intent Optional Attributes Name
type(TwoGrids), intent(inout) :: f2c
Calls
Called by
Call graph
wavenumber_fwrestriction calls mg_checkreal_xy2d
mg_checkreal_xy2d calls mg_checkreal_x2d, mg_checkreal_y2d
mg_checkreal_x2d calls mpi_sendrecv
mg_checkreal_y2d calls mpi_sendrecv
fromfine2coarse calls wavenumber_fwrestriction
twogrids calls fromfine2coarse