write_data_whole – ParaMADP
write_data_whole Subroutine
MIT
96 statements
Source File
public subroutine write_data_whole(xx, yy, u)
Write the solutions
Arguments
Type Intent Optional Attributes Name
real(kind=realdp), dimension(1-LAP:nx+LAP,1-LAP:ny+LAP) :: xx
real(kind=realdp), dimension(1-LAP:nx+LAP,1-LAP:ny+LAP) :: yy
complex(kind=realdp), dimension(1-LAP:nx+LAP,1-LAP:ny+LAP) :: u
Calls
Called by
Call graph
write_data_whole calls mpi_recv, mpi_send
helmholtz_2d calls write_data_whole