Zx – ParaMADP
Zx Function
MIT
86 statements
Source File
public function Zx(x, f2c)
Interpolation of a variable from coarse to fine, by bilinear or higher-order interpolation depending on the laylers of overlapping grid points used.
Arguments
Type Intent Optional Attributes Name
complex(kind=realdp), intent(inout) :: x(1-LAP:f2c%nxc+LAP,1-LAP:f2c%nyc+LAP)
type(TwoGrids), intent(inout) :: f2c
Return Value complex(kind=realdp), (1-LAP:f2c%nxf+LAP,1-LAP:f2c%nyf+LAP)
Calls
Called by
Call graph
zx calls mg_check_xy2d
mg_check_xy2d calls mg_check_x2d, mg_check_y2d
mg_check_x2d calls mpi_sendrecv
mg_check_y2d calls mpi_sendrecv
ex calls zx, ztzx
multileveladp_px calls zx, multilevel_invey
qx calls zx, invey
ztzx calls zx
def_arnoldi calls ex
def_bicgstab calls ex
def_fullgmres calls ex, def_arnoldi
def_prefgmres calls multileveladp_px
def_px calls multileveladp_px, p_adef1x, p_defx, p_tlkmx
p_adef1x calls qx
p_defx calls qx
p_tlkmx calls qx
px calls qx
invey calls def_bicgstab, def_fullgmres
multilevel_invey calls def_prefgmres
precond_x calls def_px
full_pgcr calls precond_x
full_pgmres calls precond_x
pfgmres calls precond_x
pre_fullgmres calls precond_x, prearnoldi
pre_restartgmres calls precond_x, prearnoldi
prearnoldi calls precond_x
helmholtz_2d calls full_pgcr, full_pgmres, pfgmres, pre_fullgmres, pre_restartgmres