apply_givens_rotation – ParaMADP
apply_givens_rotation Subroutine
MIT
23 statements
Source File
public subroutine apply_givens_rotation(H, cs, sn, k)
APPLY GIVENS ROTATION
Arguments
Type Intent Optional Attributes Name
complex(kind=realdp), intent(inout), dimension(m_iter+1,m_iter) :: H
complex(kind=realdp), intent(inout), dimension(m_iter+1) :: cs
complex(kind=realdp), intent(inout), dimension(m_iter+1) :: sn
integer, intent(in) :: k
Calls
Called by
Call graph
apply_givens_rotation calls cdsqrt
full_pgmres calls apply_givens_rotation
fullgmres calls apply_givens_rotation
pfgmres calls apply_givens_rotation
pre_fullgmres calls apply_givens_rotation
pre_restartgmres calls apply_givens_rotation
restartgmres calls apply_givens_rotation
helmholtz_2d calls full_pgmres, fullgmres, pfgmres, pre_fullgmres, pre_restartgmres, restartgmres