arnoldi – ParaMADP
arnoldi Subroutine
MIT
14 statements
Source File
public subroutine arnoldi(V, H, k)
ARNOLDI precess
Arguments
Type Intent Optional Attributes Name
complex(kind=realdp), intent(inout), dimension(1-LAP:nx+LAP,1-LAP:ny+LAP,m_iter+1) :: V
complex(kind=realdp), intent(inout), dimension(m_iter+1,m_iter) :: H
integer, intent(in) :: k
Calls
Called by
Call graph
arnoldi calls dot_prod, helmholtz2d_bc, norm
dot_prod calls mpi_allreduce
helmholtz2d_bc calls check_xy2d, helmholtz2d_stencils, if_bcs
norm calls mpi_allreduce
check_xy2d calls check_x2d, check_y2d
if_bcs calls dirichlet, first_order_neum
check_x2d calls mpi_sendrecv
check_y2d calls mpi_sendrecv
fullgmres calls arnoldi
restartgmres calls arnoldi
helmholtz_2d calls fullgmres, restartgmres