cmatvec – ParaMADP
cmatvec Function
MIT
10 statements
Source File
public function cmatvec(A, v)
This is complex matrix-vector multiplication
Arguments
Type Intent Optional Attributes Name
type(matrix), intent(in) :: A
complex(kind=realdp), intent(in) :: v(:,:)
Return Value complex(kind=realdp), (size(v,1),size(v,2))
Calls
Called by
Call graph
cmatvec calls helmholtz2d_bc
helmholtz2d_bc calls check_xy2d, helmholtz2d_stencils, if_bcs
check_xy2d calls check_x2d, check_y2d
if_bcs calls dirichlet, first_order_neum
check_x2d calls mpi_sendrecv
check_y2d calls mpi_sendrecv
operator(ASTERISK) calls cmatvec