CoarseGridpara – ParaMADP
CoarseGridpara Function
MIT
19 statements
Source File
public function CoarseGridpara(f2c)
A procedure to create a Gridpara type of the coarse grid system from a given a two-grid system
Arguments
Type Intent Optional Attributes Name
type(TwoGrids), intent(inout) :: f2c
Return Value type(Gridpara)
Called by
Call graph
def_bicgstab calls coarsegridpara, ex
def_fullgmres calls coarsegridpara, ex, def_arnoldi
def_prefgmres calls coarsegridpara, multileveladp_px
ex calls coarsegridpara
def_arnoldi calls ex
invey calls def_bicgstab, def_fullgmres
multilevel_invey calls def_prefgmres
multileveladp_px calls multilevel_invey
qx calls invey
def_px calls multileveladp_px, p_adef1x, p_defx, p_tlkmx
p_adef1x calls qx
p_defx calls qx
p_tlkmx calls qx
px calls qx
precond_x calls def_px
full_pgcr calls precond_x
full_pgmres calls precond_x
pfgmres calls precond_x
pre_fullgmres calls precond_x, prearnoldi
pre_restartgmres calls precond_x, prearnoldi
prearnoldi calls precond_x
helmholtz_2d calls full_pgcr, full_pgmres, pfgmres, pre_fullgmres, pre_restartgmres