cslp2d_stencils – ParaMADP
cslp2d_stencils Subroutine
MIT
11 statements
Source File
public subroutine cslp2d_stencils(ap, an, as, aw, ae, hxhykxy2)
Computational stencils for the CSLP operator
Arguments
Type Intent Optional Attributes Name
complex(kind=realdp) :: ap
real(kind=realdp) :: an
real(kind=realdp) :: as
real(kind=realdp) :: aw
real(kind=realdp) :: ae
real(kind=realdp), intent(in) :: hxhykxy2
The value of (kh)^2, which is computed and stored in advance
Called by
Call graph
cslp_mx_nth calls cslp2d_stencils
cslp_op_bc calls cslp2d_stencils
damp_jacobi_smoother calls cslp2d_stencils
f_cycle calls cslp_op_bc, damp_jacobi_smoother, f_cycle, mg_bicgstab, mg_fullgmres, v_cycle
mg_arnoldi calls cslp_op_bc
mg_bicgstab calls cslp_op_bc
mg_fullgmres calls cslp_op_bc, mg_arnoldi
red_glk_cslp_bicgstab calls cslp_mx_nth
red_glk_cslp_gmres calls cslp_mx_nth
v_cycle calls cslp_op_bc, damp_jacobi_smoother, mg_bicgstab, mg_fullgmres, v_cycle
krylovcslp_invmhx calls red_glk_cslp_gmres
mgcslp_invmhx calls f_cycle, v_cycle
mgcslp_invmx calls f_cycle, v_cycle
cprecon calls mgcslp_invmx
def_arnoldi calls mgcslp_invmhx, ex
def_bicgstab calls mgcslp_invmhx, ex
def_fullgmres calls mgcslp_invmhx, def_arnoldi, ex
def_prefgmres calls krylovcslp_invmhx, multileveladp_px
ex calls mgcslp_invmhx
multileveladp_px calls krylovcslp_invmhx, mgcslp_invmhx, multilevel_invey
p_adef1x calls mgcslp_invmx, qx
p_tlkmx calls mgcslp_invmx, qx
precond_x calls mgcslp_invmx, def_px
operator(SLASH) calls cprecon
def_px calls multileveladp_px, p_adef1x, p_tlkmx, p_defx
full_pgcr calls precond_x
full_pgmres calls precond_x
invey calls def_bicgstab, def_fullgmres
multilevel_invey calls def_prefgmres
pfgmres calls precond_x
pre_fullgmres calls precond_x, prearnoldi
pre_restartgmres calls precond_x, prearnoldi
prearnoldi calls precond_x
qx calls invey
helmholtz_2d calls full_pgcr, full_pgmres, pfgmres, pre_fullgmres, pre_restartgmres
p_defx calls qx
px calls qx