CSLP_Mx_nth_stencils – ParaMADP
CSLP_Mx_nth_stencils Subroutine
MIT
71 statements
Source File
public subroutine CSLP_Mx_nth_stencils(Stcl_nth, grid, ic, jc)
ReD-Glk computational stencils of the CSLP operator for differnet coarse-grid level
Arguments
Type Intent Optional Attributes Name
complex(kind=realdp) :: Stcl_nth(-3:3,-3:3)
Resulting stencils for the CSLP operator
type(Gridpara), intent(inout) :: grid
parameters for the current coarse-grid system
integer :: ic
Index for the wavenumber field
integer :: jc
Index for the wavenumber field
Calls
Called by
Call graph
cslp_mx_nth_stencils calls log2
cslp_mx_nth calls cslp_mx_nth_stencils
red_glk_cslp_bicgstab calls cslp_mx_nth
red_glk_cslp_gmres calls cslp_mx_nth
krylovcslp_invmhx calls red_glk_cslp_gmres
def_prefgmres calls krylovcslp_invmhx, multileveladp_px
multileveladp_px calls krylovcslp_invmhx, multilevel_invey
def_px calls multileveladp_px
multilevel_invey calls def_prefgmres
precond_x calls def_px
full_pgcr calls precond_x
full_pgmres calls precond_x
pfgmres calls precond_x
pre_fullgmres calls precond_x, prearnoldi
pre_restartgmres calls precond_x, prearnoldi
prearnoldi calls precond_x
helmholtz_2d calls full_pgcr, full_pgmres, pfgmres, pre_fullgmres, pre_restartgmres