DEF_prefgmres – ParaMADP
DEF_prefgmres Subroutine
MIT
101 statements
Source File
public recursive subroutine DEF_prefgmres(y, x, f2c, maximum_iterations, level, rtol)
A recursive flexible GMRES with right deflation preconditioning Be careful!!, after the whole iteration without achieving eps, then the value of j will be "maxit+1".So we need a k.
Attention: h_(i,j)=(w,v_i)=v^H*w, for complex value, so the code should be dot_product(v_i,w)
Arguments
Type Intent Optional Attributes Name
complex(kind=realdp), intent(inout) :: y(1-LAP:f2c%nxc+LAP,1-LAP:f2c%nyc+LAP)
complex(kind=realdp), intent(inout) :: x(1-LAP:f2c%nxc+LAP,1-LAP:f2c%nyc+LAP)
type(TwoGrids), intent(inout) :: f2c
integer, intent(in), optional :: maximum_iterations
integer, intent(in), optional :: level
real(kind=realdp), intent(in), optional :: rtol
Calls
Called by
Call graph
def_prefgmres calls cdsqrt, coarsegridpara, helm_ax_nth, krylovcslp_invmhx, mg_dot_prod, mg_norm, multileveladp_px
helm_ax_nth calls gridbase_extrpltghostbcs, helm_ax_nth_stencils, helmholtz2d_stencils, log2, mg_check_xy2d
krylovcslp_invmhx calls grid_destroy, gridsys_define, red_glk_cslp_gmres
mg_dot_prod calls mpi_allreduce
mg_norm calls mpi_allreduce
multileveladp_px calls helm_ax_nth, krylovcslp_invmhx, log2, mgcslp_invmhx, multilevel_invey, ztx, zx
helm_ax_nth_stencils calls log2
mg_check_xy2d calls mg_check_x2d, mg_check_y2d
mgcslp_invmhx calls grid_destroy, gridsys_define, f_cycle, v_cycle
multilevel_invey calls def_prefgmres, log2
red_glk_cslp_gmres calls cdsqrt, mg_dot_prod, mg_norm, log2, cslp_mx_nth
ztx calls mg_check_xy2d
zx calls mg_check_xy2d
cslp_mx_nth calls gridbase_extrpltghostbcs, log2, mg_check_xy2d, cslp2d_stencils, cslp_mx_nth_stencils
f_cycle calls grid_destroy, f_cycle, v_cycle, coarsegrid_create, cslp_op_bc, damp_jacobi_smoother, mg_bicgstab, mg_fullgmres, prolongation_en_correct, restriction
mg_check_x2d calls mpi_sendrecv
mg_check_y2d calls mpi_sendrecv
v_cycle calls grid_destroy, v_cycle, coarsegrid_create, cslp_op_bc, damp_jacobi_smoother, mg_bicgstab, mg_fullgmres, prolongation_en_correct, restriction
cslp_mx_nth_stencils calls log2
cslp_op_bc calls mg_check_xy2d, cslp2d_stencils, if_bcs
damp_jacobi_smoother calls mg_check_xy2d, cslp2d_stencils, if_bcs
mg_bicgstab calls mg_dot_prod, mg_norm, cslp_op_bc
mg_fullgmres calls mg_norm, cslp_op_bc, mg_apply_givens_rotation, mg_arnoldi, mg_back_substitute
prolongation_en_correct calls mg_check_xy2d
restriction calls mg_check_xy2d, mg_checkreal_xy2d
if_bcs calls dirichlet, first_order_neum
mg_apply_givens_rotation calls cdsqrt
mg_arnoldi calls mg_dot_prod, mg_norm, cslp_op_bc
mg_checkreal_xy2d calls mg_checkreal_x2d, mg_checkreal_y2d
mg_checkreal_x2d calls mpi_sendrecv
mg_checkreal_y2d calls mpi_sendrecv
def_px calls multileveladp_px
precond_x calls def_px
full_pgcr calls precond_x
full_pgmres calls precond_x
pfgmres calls precond_x
pre_fullgmres calls precond_x, prearnoldi
pre_restartgmres calls precond_x, prearnoldi
prearnoldi calls precond_x
helmholtz_2d calls full_pgcr, full_pgmres, pfgmres, pre_fullgmres, pre_restartgmres