DEF_Px – ParaMADP
DEF_Px Function
MIT
23 statements
Source File
public function DEF_Px(x)
Identifier for different deflation methods, ONLY for an input array from the default (finest) grid system A basic deflation method
Adapted deflation method, including higher-order deflation vectors
Two-level Krylov Method
Multilevel deflation method
Arguments
Type Intent Optional Attributes Name
complex(kind=realdp), dimension(1-LAP:nx+LAP,1-LAP:ny+LAP) :: x
Return Value complex(kind=realdp), dimension(1-LAP:nx+LAP,1-LAP:ny+LAP)
Calls
Called by
Call graph
def_px calls default_gridpara, multileveladp_px, p_adef1x, p_defx, p_tlkmx
multileveladp_px calls helm_ax_nth, krylovcslp_invmhx, log2, mgcslp_invmhx, multilevel_invey, ztx, zx
p_adef1x calls helm_ahx, mgcslp_invmx, qx
p_defx calls helm_ahx, qx
p_tlkmx calls helm_ahx, mgcslp_invmx, qx
helm_ahx calls helmholtz2d_bc_mg
helm_ax_nth calls log2, gridbase_extrpltghostbcs, helm_ax_nth_stencils, helmholtz2d_stencils, mg_check_xy2d
krylovcslp_invmhx calls grid_destroy, gridsys_define, red_glk_cslp_gmres
mgcslp_invmhx calls f_cycle, grid_destroy, gridsys_define, v_cycle
mgcslp_invmx calls f_cycle, finestgrid_define, grid_destroy, v_cycle
multilevel_invey calls log2, def_prefgmres
qx calls ztx, zx, invey
ztx calls mg_check_xy2d
zx calls mg_check_xy2d
def_prefgmres calls multileveladp_px, helm_ax_nth, krylovcslp_invmhx, cdsqrt, coarsegridpara, mg_dot_prod, mg_norm
f_cycle calls f_cycle, grid_destroy, v_cycle, coarsegrid_create, cslp_op_bc, damp_jacobi_smoother, mg_bicgstab, mg_fullgmres, prolongation_en_correct, restriction
helm_ax_nth_stencils calls log2
helmholtz2d_bc_mg calls helmholtz2d_stencils, mg_check_xy2d, if_bcs
invey calls def_bicgstab, def_fullgmres
mg_check_xy2d calls mg_check_x2d, mg_check_y2d
red_glk_cslp_gmres calls log2, cdsqrt, cslp_mx_nth, mg_dot_prod, mg_norm
v_cycle calls grid_destroy, v_cycle, coarsegrid_create, cslp_op_bc, damp_jacobi_smoother, mg_bicgstab, mg_fullgmres, prolongation_en_correct, restriction
cslp_mx_nth calls log2, gridbase_extrpltghostbcs, mg_check_xy2d, cslp2d_stencils, cslp_mx_nth_stencils
cslp_op_bc calls mg_check_xy2d, if_bcs, cslp2d_stencils
damp_jacobi_smoother calls mg_check_xy2d, if_bcs, cslp2d_stencils
def_bicgstab calls mgcslp_invmhx, coarsegridpara, mg_dot_prod, mg_norm, ex
def_fullgmres calls mgcslp_invmhx, coarsegridpara, mg_norm, def_apply_givens_rotation, def_arnoldi, def_back_substitute, ex
if_bcs calls dirichlet, first_order_neum
mg_bicgstab calls cslp_op_bc, mg_dot_prod, mg_norm
mg_check_x2d calls mpi_sendrecv
mg_check_y2d calls mpi_sendrecv
mg_dot_prod calls mpi_allreduce
mg_fullgmres calls cslp_op_bc, mg_norm, mg_apply_givens_rotation, mg_arnoldi, mg_back_substitute
mg_norm calls mpi_allreduce
prolongation_en_correct calls mg_check_xy2d
restriction calls mg_check_xy2d, mg_checkreal_xy2d
cslp_mx_nth_stencils calls log2
def_apply_givens_rotation calls cdsqrt
def_arnoldi calls mgcslp_invmhx, mg_dot_prod, mg_norm, ex
ex calls helm_ahx, mgcslp_invmhx, ztx, zx, coarsegridpara, helm_a2hx, ztzx
mg_apply_givens_rotation calls cdsqrt
mg_arnoldi calls cslp_op_bc, mg_dot_prod, mg_norm
mg_checkreal_xy2d calls mg_checkreal_x2d, mg_checkreal_y2d
helm_a2hx calls helmholtz2d_bc_mg, helmholtz2d_o4cmpct, helmholtz2d_red_glk
mg_checkreal_x2d calls mpi_sendrecv
mg_checkreal_y2d calls mpi_sendrecv
ztzx calls ztx, zx
helmholtz2d_o4cmpct calls mg_check_xy2d
helmholtz2d_red_glk calls helmholtz2d_stencils, mg_check_xy2d, extrpltghostbcs, red_glk_stencils
precond_x calls def_px
full_pgcr calls precond_x
full_pgmres calls precond_x
pfgmres calls precond_x
pre_fullgmres calls precond_x, prearnoldi
pre_restartgmres calls precond_x, prearnoldi
prearnoldi calls precond_x
helmholtz_2d calls full_pgcr, full_pgmres, pfgmres, pre_fullgmres, pre_restartgmres