default_gridpara – ParaMADP
default_gridpara Subroutine
MIT
19 statements
Source File
public subroutine default_gridpara(finestgrid)
This is a rountine to define the default finest Gridpara from the common grid parameters of the whole project
Arguments
Type Intent Optional Attributes Name
type(Gridpara), intent(inout) :: finestgrid
Called by
Call graph
def_px calls default_gridpara
precond_x calls def_px
full_pgcr calls precond_x
full_pgmres calls precond_x
pfgmres calls precond_x
pre_fullgmres calls precond_x, prearnoldi
pre_restartgmres calls precond_x, prearnoldi
prearnoldi calls precond_x
helmholtz_2d calls full_pgcr, full_pgmres, pfgmres, pre_fullgmres, pre_restartgmres