dot_prod – ParaMADP
dot_prod Function
MIT
13 statements
Source File
public function dot_prod(v, w)
Compute the do product of two complex variables, ONLY for the default grid system.
Arguments
Type Intent Optional Attributes Name
complex(kind=realdp), intent(in), dimension(1-LAP:nx+LAP,1-LAP:ny+LAP) :: v
complex(kind=realdp), intent(in), dimension(1-LAP:nx+LAP,1-LAP:ny+LAP) :: w
Return Value complex(kind=realdp)
Calls
Called by
Call graph
dot_prod calls mpi_allreduce
arnoldi calls dot_prod
full_pgcr calls dot_prod
full_pgmres calls dot_prod
pfgmres calls dot_prod
prearnoldi calls dot_prod
fullgmres calls arnoldi
pre_fullgmres calls prearnoldi
pre_restartgmres calls prearnoldi
restartgmres calls arnoldi
helmholtz_2d calls full_pgcr, full_pgmres, pfgmres, fullgmres, pre_fullgmres, pre_restartgmres, restartgmres