gridsys_define – ParaMADP
gridsys_define Subroutine
MIT
26 statements
Source File
public subroutine gridsys_define(grid, basegridsys)
This is a routine that define a GridSystem type from the grid parameters of a data type Gridpara One can find the differnece of GridSystem and Gridpara
Arguments
Type Intent Optional Attributes Name
type(Gridpara) :: grid
type(GridSystem) :: basegridsys
Called by
Call graph
krylovcslp_invmhx calls gridsys_define
mgcslp_invmhx calls gridsys_define
def_arnoldi calls mgcslp_invmhx, ex
def_bicgstab calls mgcslp_invmhx, ex
def_fullgmres calls mgcslp_invmhx, def_arnoldi, ex
def_prefgmres calls krylovcslp_invmhx, multileveladp_px
ex calls mgcslp_invmhx
multileveladp_px calls krylovcslp_invmhx, mgcslp_invmhx, multilevel_invey
def_px calls multileveladp_px, p_adef1x, p_defx, p_tlkmx
invey calls def_bicgstab, def_fullgmres
multilevel_invey calls def_prefgmres
precond_x calls def_px
qx calls invey
full_pgcr calls precond_x
full_pgmres calls precond_x
p_adef1x calls qx
p_defx calls qx
p_tlkmx calls qx
pfgmres calls precond_x
pre_fullgmres calls precond_x, prearnoldi
pre_restartgmres calls precond_x, prearnoldi
prearnoldi calls precond_x
px calls qx
helmholtz_2d calls full_pgcr, full_pgmres, pfgmres, pre_fullgmres, pre_restartgmres