Helm_Ahx – ParaMADP
Helm_Ahx Function
MIT
8 statements
Source File
public function Helm_Ahx(x, f2c)
A function that performs the Helmholtz operator on the fine grid of the two-grid system, by ReD-O2 method
Arguments
Type Intent Optional Attributes Name
complex(kind=realdp), intent(inout) :: x(1-LAP:f2c%nxf+LAP,1-LAP:f2c%nyf+LAP)
type(TwoGrids), intent(inout) :: f2c
Return Value complex(kind=realdp), (1-LAP:f2c%nxf+LAP,1-LAP:f2c%nyf+LAP)
Calls
Called by
Call graph
helm_ahx calls helmholtz2d_bc_mg
helmholtz2d_bc_mg calls helmholtz2d_stencils, if_bcs, mg_check_xy2d
if_bcs calls dirichlet, first_order_neum
mg_check_xy2d calls mg_check_x2d, mg_check_y2d
mg_check_x2d calls mpi_sendrecv
mg_check_y2d calls mpi_sendrecv
ex calls helm_ahx
p_adef1x calls helm_ahx, qx
p_defx calls helm_ahx, qx
p_tlkmx calls helm_ahx, qx
px calls helm_ahx, qx
def_arnoldi calls ex
def_bicgstab calls ex
def_fullgmres calls ex, def_arnoldi
def_px calls p_adef1x, p_defx, p_tlkmx
invey calls def_bicgstab, def_fullgmres
precond_x calls def_px
full_pgcr calls precond_x
full_pgmres calls precond_x
pfgmres calls precond_x
pre_fullgmres calls precond_x, prearnoldi
pre_restartgmres calls precond_x, prearnoldi
prearnoldi calls precond_x
qx calls invey
helmholtz_2d calls full_pgcr, full_pgmres, pfgmres, pre_fullgmres, pre_restartgmres