Helm_Ax_nth_stencils – ParaMADP
Helm_Ax_nth_stencils Subroutine
MIT
71 statements
Source File
public subroutine Helm_Ax_nth_stencils(Stcl_nth, grid, ic, jc)
ReD-Glk computational stencils of the Helmholtz operator for differnet coarse-grid level Default 2nd-ordr stencils
Arguments
Type Intent Optional Attributes Name
complex(kind=realdp) :: Stcl_nth(-3:3,-3:3)
Resulting stencils for the Helmholtz operator
type(Gridpara), intent(inout) :: grid
parameters for the current coarse-grid system
integer :: ic
Index for the wavenumber field
integer :: jc
Index for the wavenumber field
Calls
Called by
Call graph
helm_ax_nth_stencils calls log2
helm_ax_nth calls helm_ax_nth_stencils
def_prefgmres calls helm_ax_nth, multileveladp_px
multileveladp_px calls helm_ax_nth, multilevel_invey
def_px calls multileveladp_px
multilevel_invey calls def_prefgmres
precond_x calls def_px
full_pgcr calls precond_x
full_pgmres calls precond_x
pfgmres calls precond_x
pre_fullgmres calls precond_x, prearnoldi
pre_restartgmres calls precond_x, prearnoldi
prearnoldi calls precond_x
helmholtz_2d calls full_pgcr, full_pgmres, pfgmres, pre_fullgmres, pre_restartgmres