Helmholtz2d_ReD_Glk – ParaMADP
Helmholtz2d_ReD_Glk Subroutine
MIT
73 statements
Source File
public subroutine Helmholtz2d_ReD_Glk(v_in, v_out, f2c)
A coarse-grid Helmholtz operator for two-level deflation, descretized by ReD-GLK FD scheme fill in a layer of ghost grid points by boundary conditions
The boundary keeps 2nd-order finite difference scheme using five points stencils
Arguments
Type Intent Optional Attributes Name
complex(kind=realdp), intent(inout) :: v_in(1-LAP:f2c%nxc+LAP,1-LAP:f2c%nyc+LAP)
complex(kind=realdp), intent(inout) :: v_out(1-LAP:f2c%nxc+LAP,1-LAP:f2c%nyc+LAP)
type(TwoGrids), intent(inout) :: f2c
Calls
Called by
Call graph
helmholtz2d_red_glk calls extrpltghostbcs, helmholtz2d_stencils, mg_check_xy2d, red_glk_stencils
mg_check_xy2d calls mg_check_x2d, mg_check_y2d
mg_check_x2d calls mpi_sendrecv
mg_check_y2d calls mpi_sendrecv
helm_a2hx calls helmholtz2d_red_glk
ex calls helm_a2hx
def_arnoldi calls ex
def_bicgstab calls ex
def_fullgmres calls ex, def_arnoldi
invey calls def_bicgstab, def_fullgmres
qx calls invey
p_adef1x calls qx
p_defx calls qx
p_tlkmx calls qx
px calls qx
def_px calls p_adef1x, p_defx, p_tlkmx
precond_x calls def_px
full_pgcr calls precond_x
full_pgmres calls precond_x
pfgmres calls precond_x
pre_fullgmres calls precond_x, prearnoldi
pre_restartgmres calls precond_x, prearnoldi
prearnoldi calls precond_x
helmholtz_2d calls full_pgcr, full_pgmres, pfgmres, pre_fullgmres, pre_restartgmres