Helmholtz2d_BC – ParaMADP
Helmholtz2d_BC Subroutine
MIT
51 statements
Source File
public subroutine Helmholtz2d_BC(v_in, v_out)
matrix-free Helmholtz operator, ONLY for the default gird system First deal with the boundary grid points and then the internals
Arguments
Type Intent Optional Attributes Name
complex(kind=realdp), intent(inout), dimension(1-LAP:nx+LAP,1-LAP:ny+LAP) :: v_in
complex(kind=realdp), intent(inout), dimension(1-LAP:nx+LAP,1-LAP:ny+LAP) :: v_out
Calls
Called by
Call graph
helmholtz2d_bc calls check_xy2d, helmholtz2d_stencils, if_bcs
check_xy2d calls check_x2d, check_y2d
if_bcs calls dirichlet, first_order_neum
check_x2d calls mpi_sendrecv
check_y2d calls mpi_sendrecv
arnoldi calls helmholtz2d_bc
cmatvec calls helmholtz2d_bc
full_pgcr calls helmholtz2d_bc
full_pgmres calls helmholtz2d_bc
fullgmres calls helmholtz2d_bc, arnoldi
pfgmres calls helmholtz2d_bc
pre_fullgmres calls helmholtz2d_bc, prearnoldi
pre_restartgmres calls helmholtz2d_bc, prearnoldi
prearnoldi calls helmholtz2d_bc
restartgmres calls helmholtz2d_bc, arnoldi
operator(ASTERISK) calls cmatvec
helmholtz_2d calls full_pgcr, full_pgmres, fullgmres, pfgmres, pre_fullgmres, pre_restartgmres, restartgmres