if_BCs – ParaMADP
if_BCs Subroutine
MIT
15 statements
Source File
public subroutine if_BCs(ap, an, as, aw, ae, i, j, ni, nj, hx_c, hy_c, kxy)
Determine which BC, for specified coarse grid system
Arguments
Type Intent Optional Attributes Name
complex(kind=realdp) :: ap
real(kind=realdp) :: an
real(kind=realdp) :: as
real(kind=realdp) :: aw
real(kind=realdp) :: ae
integer, intent(in) :: i
integer, intent(in) :: j
integer, intent(in) :: ni
integer, intent(in) :: nj
real(kind=realdp), intent(in) :: hx_c
real(kind=realdp), intent(in) :: hy_c
real(kind=realdp), intent(in) :: kxy
Calls
Called by
Call graph
if_bcs calls dirichlet, first_order_neum
cslp_op_bc calls if_bcs
damp_jacobi_smoother calls if_bcs
helmholtz2d_bc calls if_bcs
helmholtz2d_bc_mg calls if_bcs
arnoldi calls helmholtz2d_bc
cmatvec calls helmholtz2d_bc
f_cycle calls cslp_op_bc, damp_jacobi_smoother, f_cycle, mg_bicgstab, mg_fullgmres, v_cycle
full_pgcr calls helmholtz2d_bc, precond_x
full_pgmres calls helmholtz2d_bc, precond_x
fullgmres calls helmholtz2d_bc, arnoldi
helm_a2hx calls helmholtz2d_bc_mg
helm_ahx calls helmholtz2d_bc_mg
mg_arnoldi calls cslp_op_bc
mg_bicgstab calls cslp_op_bc
mg_fullgmres calls cslp_op_bc, mg_arnoldi
pfgmres calls helmholtz2d_bc, precond_x
pre_fullgmres calls helmholtz2d_bc, prearnoldi, precond_x
pre_restartgmres calls helmholtz2d_bc, prearnoldi, precond_x
prearnoldi calls helmholtz2d_bc, precond_x
restartgmres calls helmholtz2d_bc, arnoldi
v_cycle calls cslp_op_bc, damp_jacobi_smoother, mg_bicgstab, mg_fullgmres, v_cycle
operator(ASTERISK) calls cmatvec
ex calls helm_a2hx, helm_ahx, mgcslp_invmhx
mgcslp_invmhx calls f_cycle, v_cycle
mgcslp_invmx calls f_cycle, v_cycle
p_adef1x calls helm_ahx, mgcslp_invmx, qx
p_defx calls helm_ahx, qx
p_tlkmx calls helm_ahx, mgcslp_invmx, qx
px calls helm_ahx, qx
helmholtz_2d calls full_pgcr, full_pgmres, fullgmres, pfgmres, pre_fullgmres, pre_restartgmres, restartgmres
cprecon calls mgcslp_invmx
def_arnoldi calls ex, mgcslp_invmhx
def_bicgstab calls ex, mgcslp_invmhx
def_fullgmres calls ex, mgcslp_invmhx, def_arnoldi
def_px calls p_adef1x, p_defx, p_tlkmx, multileveladp_px
multileveladp_px calls mgcslp_invmhx, multilevel_invey
precond_x calls mgcslp_invmx, def_px
operator(SLASH) calls cprecon
def_prefgmres calls multileveladp_px
invey calls def_bicgstab, def_fullgmres
multilevel_invey calls def_prefgmres
qx calls invey