invEy – ParaMADP
invEy Function
MIT
12 statements
Source File
public function invEy(y, f2c)
Invert the coarse-grid operator for two-level delfation method, by using GMRES or Bi-CGSTAB determined by the specified maximum number of iterations on the coarse grid
Arguments
Type Intent Optional Attributes Name
complex(kind=realdp), intent(inout) :: y(1-LAP:f2c%nxc+LAP,1-LAP:f2c%nyc+LAP)
type(TwoGrids), intent(inout) :: f2c
Return Value complex(kind=realdp), (1-LAP:f2c%nxc+LAP,1-LAP:f2c%nyc+LAP)
Calls
Called by
Call graph
invey calls def_bicgstab, def_fullgmres
def_bicgstab calls coarsegridpara, ex, mg_dot_prod, mg_norm, mgcslp_invmhx
def_fullgmres calls coarsegridpara, def_apply_givens_rotation, def_arnoldi, def_back_substitute, ex, mg_norm, mgcslp_invmhx
def_apply_givens_rotation calls cdsqrt
def_arnoldi calls ex, mg_dot_prod, mg_norm, mgcslp_invmhx
ex calls coarsegridpara, mgcslp_invmhx, helm_a2hx, helm_ahx, ztx, ztzx, zx
mg_dot_prod calls mpi_allreduce
mg_norm calls mpi_allreduce
mgcslp_invmhx calls f_cycle, grid_destroy, gridsys_define, v_cycle
f_cycle calls f_cycle, grid_destroy, v_cycle, coarsegrid_create, cslp_op_bc, damp_jacobi_smoother, mg_bicgstab, mg_fullgmres, prolongation_en_correct, restriction
helm_a2hx calls helmholtz2d_bc_mg, helmholtz2d_o4cmpct, helmholtz2d_red_glk
helm_ahx calls helmholtz2d_bc_mg
v_cycle calls grid_destroy, v_cycle, coarsegrid_create, cslp_op_bc, damp_jacobi_smoother, mg_bicgstab, mg_fullgmres, prolongation_en_correct, restriction
ztx calls mg_check_xy2d
ztzx calls ztx, zx
zx calls mg_check_xy2d
cslp_op_bc calls mg_check_xy2d, cslp2d_stencils, if_bcs
damp_jacobi_smoother calls mg_check_xy2d, cslp2d_stencils, if_bcs
helmholtz2d_bc_mg calls mg_check_xy2d, helmholtz2d_stencils, if_bcs
helmholtz2d_o4cmpct calls mg_check_xy2d
helmholtz2d_red_glk calls mg_check_xy2d, extrpltghostbcs, helmholtz2d_stencils, red_glk_stencils
mg_bicgstab calls mg_dot_prod, mg_norm, cslp_op_bc
mg_check_xy2d calls mg_check_x2d, mg_check_y2d
mg_fullgmres calls mg_norm, cslp_op_bc, mg_apply_givens_rotation, mg_arnoldi, mg_back_substitute
prolongation_en_correct calls mg_check_xy2d
restriction calls mg_check_xy2d, mg_checkreal_xy2d
if_bcs calls dirichlet, first_order_neum
mg_apply_givens_rotation calls cdsqrt
mg_arnoldi calls mg_dot_prod, mg_norm, cslp_op_bc
mg_check_x2d calls mpi_sendrecv
mg_check_y2d calls mpi_sendrecv
mg_checkreal_xy2d calls mg_checkreal_x2d, mg_checkreal_y2d
mg_checkreal_x2d calls mpi_sendrecv
mg_checkreal_y2d calls mpi_sendrecv
qx calls invey
p_adef1x calls qx
p_defx calls qx
p_tlkmx calls qx
px calls qx
def_px calls p_adef1x, p_defx, p_tlkmx
precond_x calls def_px
full_pgcr calls precond_x
full_pgmres calls precond_x
pfgmres calls precond_x
pre_fullgmres calls precond_x, prearnoldi
pre_restartgmres calls precond_x, prearnoldi
prearnoldi calls precond_x
helmholtz_2d calls full_pgcr, full_pgmres, pfgmres, pre_fullgmres, pre_restartgmres