KrylovCSLP_invMHx – ParaMADP
KrylovCSLP_invMHx Function
MIT
16 statements
Source File
public function KrylovCSLP_invMHx(b_in, grid)
Krylov-based CSLP, starts from the a specified grid sysyem Choose Bi-CGSATB or GMRES by uncomment or comment
Arguments
Type Intent Optional Attributes Name
complex(kind=realdp), dimension(1-LAP:grid%nx+LAP,1-LAP:grid%ny+LAP) :: b_in
type(Gridpara) :: grid
A data type that collect some parameters of a system
Return Value complex(kind=realdp), dimension(1-LAP:grid%nx+LAP,1-LAP:grid%ny+LAP)
Calls
Called by
Call graph
krylovcslp_invmhx calls grid_destroy, gridsys_define, red_glk_cslp_gmres
red_glk_cslp_gmres calls cdsqrt, cslp_mx_nth, log2, mg_dot_prod, mg_norm
cslp_mx_nth calls log2, cslp2d_stencils, cslp_mx_nth_stencils, gridbase_extrpltghostbcs, mg_check_xy2d
mg_dot_prod calls mpi_allreduce
mg_norm calls mpi_allreduce
cslp_mx_nth_stencils calls log2
mg_check_xy2d calls mg_check_x2d, mg_check_y2d
mg_check_x2d calls mpi_sendrecv
mg_check_y2d calls mpi_sendrecv
def_prefgmres calls krylovcslp_invmhx, multileveladp_px
multileveladp_px calls krylovcslp_invmhx, multilevel_invey
def_px calls multileveladp_px
multilevel_invey calls def_prefgmres
precond_x calls def_px
full_pgcr calls precond_x
full_pgmres calls precond_x
pfgmres calls precond_x
pre_fullgmres calls precond_x, prearnoldi
pre_restartgmres calls precond_x, prearnoldi
prearnoldi calls precond_x
helmholtz_2d calls full_pgcr, full_pgmres, pfgmres, pre_fullgmres, pre_restartgmres