mg_apply_givens_rotation – ParaMADP
mg_apply_givens_rotation Subroutine
MIT
23 statements
Source File
public subroutine mg_apply_givens_rotation(H, cs, sn, k)
This is routine to perform apply_givens_rotation
Arguments
Type Intent Optional Attributes Name
complex(kind=realdp), intent(inout), dimension(cslp_mg_miter+1,cslp_mg_miter) :: H
complex(kind=realdp), intent(inout), dimension(cslp_mg_miter+1) :: cs
complex(kind=realdp), intent(inout), dimension(cslp_mg_miter+1) :: sn
integer, intent(in) :: k
Calls
Called by
Call graph
mg_apply_givens_rotation calls cdsqrt
mg_fullgmres calls mg_apply_givens_rotation
f_cycle calls mg_fullgmres, f_cycle, v_cycle
v_cycle calls mg_fullgmres, v_cycle
mgcslp_invmhx calls f_cycle, v_cycle
mgcslp_invmx calls f_cycle, v_cycle
cprecon calls mgcslp_invmx
def_arnoldi calls mgcslp_invmhx, ex
def_bicgstab calls mgcslp_invmhx, ex
def_fullgmres calls mgcslp_invmhx, def_arnoldi, ex
ex calls mgcslp_invmhx
multileveladp_px calls mgcslp_invmhx, multilevel_invey
p_adef1x calls mgcslp_invmx, qx
p_tlkmx calls mgcslp_invmx, qx
precond_x calls mgcslp_invmx, def_px
operator(SLASH) calls cprecon
def_prefgmres calls multileveladp_px
def_px calls multileveladp_px, p_adef1x, p_tlkmx, p_defx
full_pgcr calls precond_x
full_pgmres calls precond_x
invey calls def_bicgstab, def_fullgmres
pfgmres calls precond_x
pre_fullgmres calls precond_x, prearnoldi
pre_restartgmres calls precond_x, prearnoldi
prearnoldi calls precond_x
multilevel_invey calls def_prefgmres
qx calls invey
helmholtz_2d calls full_pgcr, full_pgmres, pfgmres, pre_fullgmres, pre_restartgmres
p_defx calls qx
px calls qx