mg_dot_prod – ParaMADP
mg_dot_prod Function
MIT
14 statements
Source File
public function mg_dot_prod(v, w, ni, nj)
Compute the dot product of two complex variables, for a coarse-grid system. Note that the dimension is not specified here, it means it calculate all the elements
Arguments
Type Intent Optional Attributes Name
complex(kind=realdp), intent(in), dimension(1-LAP:ni+LAP,1-LAP:nj+LAP) :: v
complex(kind=realdp), intent(in), dimension(1-LAP:ni+LAP,1-LAP:nj+LAP) :: w
integer, intent(in) :: ni
ni, nj: grid size of the subdomain on the current coarse grid level
integer, intent(in) :: nj
ni, nj: grid size of the subdomain on the current coarse grid level
Return Value complex(kind=realdp)
Calls
Called by
Call graph
mg_dot_prod calls mpi_allreduce
def_arnoldi calls mg_dot_prod, mgcslp_invmhx, ex
def_bicgstab calls mg_dot_prod, mgcslp_invmhx, ex
def_prefgmres calls mg_dot_prod, krylovcslp_invmhx, multileveladp_px
mg_arnoldi calls mg_dot_prod
mg_bicgstab calls mg_dot_prod
red_glk_cslp_bicgstab calls mg_dot_prod
red_glk_cslp_gmres calls mg_dot_prod
def_fullgmres calls def_arnoldi, mgcslp_invmhx, ex
f_cycle calls mg_bicgstab, f_cycle, mg_fullgmres, v_cycle
invey calls def_bicgstab, def_fullgmres
krylovcslp_invmhx calls red_glk_cslp_gmres
mg_fullgmres calls mg_arnoldi
multilevel_invey calls def_prefgmres
v_cycle calls mg_bicgstab, mg_fullgmres, v_cycle
mgcslp_invmhx calls f_cycle, v_cycle
mgcslp_invmx calls f_cycle, v_cycle
multileveladp_px calls krylovcslp_invmhx, multilevel_invey, mgcslp_invmhx
qx calls invey
cprecon calls mgcslp_invmx
def_px calls multileveladp_px, p_adef1x, p_defx, p_tlkmx
ex calls mgcslp_invmhx
p_adef1x calls mgcslp_invmx, qx
p_defx calls qx
p_tlkmx calls mgcslp_invmx, qx
precond_x calls mgcslp_invmx, def_px
px calls qx
operator(SLASH) calls cprecon
full_pgcr calls precond_x
full_pgmres calls precond_x
pfgmres calls precond_x
pre_fullgmres calls precond_x, prearnoldi
pre_restartgmres calls precond_x, prearnoldi
prearnoldi calls precond_x
helmholtz_2d calls full_pgcr, full_pgmres, pfgmres, pre_fullgmres, pre_restartgmres