mg_norm – ParaMADP
mg_norm Function
MIT
14 statements
Source File
public function mg_norm(v, ni, nj)
Compute the L2-norm of a complex variable, for a coarse-grid system.
Arguments
Type Intent Optional Attributes Name
complex(kind=realdp), intent(in), dimension(1-LAP:ni+LAP,1-LAP:nj+LAP) :: v
integer, intent(in) :: ni
ni, nj: grid size of the subdomain on the current coarse grid level
integer, intent(in) :: nj
ni, nj: grid size of the subdomain on the current coarse grid level
Return Value real(kind=realdp)
Calls
Called by
Call graph
mg_norm calls mpi_allreduce
def_arnoldi calls mg_norm, mgcslp_invmhx, ex
def_bicgstab calls mg_norm, mgcslp_invmhx, ex
def_fullgmres calls mg_norm, def_arnoldi, mgcslp_invmhx, ex
def_prefgmres calls mg_norm, krylovcslp_invmhx, multileveladp_px
mg_arnoldi calls mg_norm
mg_bicgstab calls mg_norm
mg_fullgmres calls mg_norm, mg_arnoldi
red_glk_cslp_bicgstab calls mg_norm
red_glk_cslp_gmres calls mg_norm
f_cycle calls mg_bicgstab, mg_fullgmres, f_cycle, v_cycle
invey calls def_bicgstab, def_fullgmres
krylovcslp_invmhx calls red_glk_cslp_gmres
multilevel_invey calls def_prefgmres
v_cycle calls mg_bicgstab, mg_fullgmres, v_cycle
mgcslp_invmhx calls f_cycle, v_cycle
mgcslp_invmx calls f_cycle, v_cycle
multileveladp_px calls krylovcslp_invmhx, multilevel_invey, mgcslp_invmhx
qx calls invey
cprecon calls mgcslp_invmx
def_px calls multileveladp_px, p_adef1x, p_defx, p_tlkmx
ex calls mgcslp_invmhx
p_adef1x calls mgcslp_invmx, qx
p_defx calls qx
p_tlkmx calls mgcslp_invmx, qx
precond_x calls mgcslp_invmx, def_px
px calls qx
operator(SLASH) calls cprecon
full_pgcr calls precond_x
full_pgmres calls precond_x
pfgmres calls precond_x
pre_fullgmres calls precond_x, prearnoldi
pre_restartgmres calls precond_x, prearnoldi
prearnoldi calls precond_x
helmholtz_2d calls full_pgcr, full_pgmres, pfgmres, pre_fullgmres, pre_restartgmres