MultiLevelADP_Px – ParaMADP
MultiLevelADP_Px Function
MIT
38 statements
Source File
public recursive function MultiLevelADP_Px(x, grid)
Multilevel deflation preconditioning (MADP) Multigrid-based CSLP on the finest and second level Krylov-based CSLP on the finest and second level
Arguments
Type Intent Optional Attributes Name
complex(kind=realdp) :: x(1-LAP:grid%nx+LAP,1-LAP:grid%ny+LAP)
type(Gridpara), intent(inout) :: grid
Return Value complex(kind=realdp), (1-LAP:grid%nx+LAP,1-LAP:grid%ny+LAP)
Calls
Called by
Call graph
multileveladp_px calls helm_ax_nth, krylovcslp_invmhx, log2, mgcslp_invmhx, multilevel_invey, ztx, zx
helm_ax_nth calls log2, gridbase_extrpltghostbcs, helm_ax_nth_stencils, helmholtz2d_stencils, mg_check_xy2d
krylovcslp_invmhx calls grid_destroy, gridsys_define, red_glk_cslp_gmres
mgcslp_invmhx calls f_cycle, grid_destroy, gridsys_define, v_cycle
multilevel_invey calls log2, def_prefgmres
ztx calls mg_check_xy2d
zx calls mg_check_xy2d
def_prefgmres calls multileveladp_px, helm_ax_nth, krylovcslp_invmhx, cdsqrt, coarsegridpara, mg_dot_prod, mg_norm
f_cycle calls f_cycle, grid_destroy, v_cycle, coarsegrid_create, cslp_op_bc, damp_jacobi_smoother, mg_bicgstab, mg_fullgmres, prolongation_en_correct, restriction
helm_ax_nth_stencils calls log2
mg_check_xy2d calls mg_check_x2d, mg_check_y2d
red_glk_cslp_gmres calls log2, cdsqrt, cslp_mx_nth, mg_dot_prod, mg_norm
v_cycle calls grid_destroy, v_cycle, coarsegrid_create, cslp_op_bc, damp_jacobi_smoother, mg_bicgstab, mg_fullgmres, prolongation_en_correct, restriction
cslp_mx_nth calls log2, gridbase_extrpltghostbcs, mg_check_xy2d, cslp2d_stencils, cslp_mx_nth_stencils
cslp_op_bc calls mg_check_xy2d, cslp2d_stencils, if_bcs
damp_jacobi_smoother calls mg_check_xy2d, cslp2d_stencils, if_bcs
mg_bicgstab calls cslp_op_bc, mg_dot_prod, mg_norm
mg_check_x2d calls mpi_sendrecv
mg_check_y2d calls mpi_sendrecv
mg_dot_prod calls mpi_allreduce
mg_fullgmres calls cslp_op_bc, mg_norm, mg_apply_givens_rotation, mg_arnoldi, mg_back_substitute
mg_norm calls mpi_allreduce
prolongation_en_correct calls mg_check_xy2d
restriction calls mg_check_xy2d, mg_checkreal_xy2d
cslp_mx_nth_stencils calls log2
if_bcs calls dirichlet, first_order_neum
mg_apply_givens_rotation calls cdsqrt
mg_arnoldi calls cslp_op_bc, mg_dot_prod, mg_norm
mg_checkreal_xy2d calls mg_checkreal_x2d, mg_checkreal_y2d
mg_checkreal_x2d calls mpi_sendrecv
mg_checkreal_y2d calls mpi_sendrecv
def_px calls multileveladp_px
precond_x calls def_px
full_pgcr calls precond_x
full_pgmres calls precond_x
pfgmres calls precond_x
pre_fullgmres calls precond_x, prearnoldi
pre_restartgmres calls precond_x, prearnoldi
prearnoldi calls precond_x
helmholtz_2d calls full_pgcr, full_pgmres, pfgmres, pre_fullgmres, pre_restartgmres