MultiLevel_invEy – ParaMADP
MultiLevel_invEy Function
MIT
42 statements
Source File
public recursive function MultiLevel_invEy(y, f2c)
A recursive function to invert the coarse-level operators for multilevel delfation methods, by using preconditioned FGMRES
Arguments
Type Intent Optional Attributes Name
complex(kind=realdp), intent(inout) :: y(1-LAP:f2c%nxc+LAP,1-LAP:f2c%nyc+LAP)
type(TwoGrids), intent(inout) :: f2c
Return Value complex(kind=realdp), (1-LAP:f2c%nxc+LAP,1-LAP:f2c%nyc+LAP)
Calls
Called by
Call graph
multilevel_invey calls def_prefgmres, log2
def_prefgmres calls cdsqrt, coarsegridpara, helm_ax_nth, krylovcslp_invmhx, mg_dot_prod, mg_norm, multileveladp_px
helm_ax_nth calls log2, gridbase_extrpltghostbcs, helm_ax_nth_stencils, helmholtz2d_stencils, mg_check_xy2d
krylovcslp_invmhx calls grid_destroy, gridsys_define, red_glk_cslp_gmres
mg_dot_prod calls mpi_allreduce
mg_norm calls mpi_allreduce
multileveladp_px calls multilevel_invey, log2, helm_ax_nth, krylovcslp_invmhx, mgcslp_invmhx, ztx, zx
helm_ax_nth_stencils calls log2
mg_check_xy2d calls mg_check_x2d, mg_check_y2d
mgcslp_invmhx calls grid_destroy, gridsys_define, f_cycle, v_cycle
red_glk_cslp_gmres calls log2, cdsqrt, mg_dot_prod, mg_norm, cslp_mx_nth
ztx calls mg_check_xy2d
zx calls mg_check_xy2d
cslp_mx_nth calls log2, gridbase_extrpltghostbcs, mg_check_xy2d, cslp2d_stencils, cslp_mx_nth_stencils
f_cycle calls grid_destroy, f_cycle, v_cycle, coarsegrid_create, cslp_op_bc, damp_jacobi_smoother, mg_bicgstab, mg_fullgmres, prolongation_en_correct, restriction
mg_check_x2d calls mpi_sendrecv
mg_check_y2d calls mpi_sendrecv
v_cycle calls grid_destroy, v_cycle, coarsegrid_create, cslp_op_bc, damp_jacobi_smoother, mg_bicgstab, mg_fullgmres, prolongation_en_correct, restriction
cslp_mx_nth_stencils calls log2
cslp_op_bc calls mg_check_xy2d, cslp2d_stencils, if_bcs
damp_jacobi_smoother calls mg_check_xy2d, cslp2d_stencils, if_bcs
mg_bicgstab calls mg_dot_prod, mg_norm, cslp_op_bc
mg_fullgmres calls mg_norm, cslp_op_bc, mg_apply_givens_rotation, mg_arnoldi, mg_back_substitute
prolongation_en_correct calls mg_check_xy2d
restriction calls mg_check_xy2d, mg_checkreal_xy2d
if_bcs calls dirichlet, first_order_neum
mg_apply_givens_rotation calls cdsqrt
mg_arnoldi calls mg_dot_prod, mg_norm, cslp_op_bc
mg_checkreal_xy2d calls mg_checkreal_x2d, mg_checkreal_y2d
mg_checkreal_x2d calls mpi_sendrecv
mg_checkreal_y2d calls mpi_sendrecv
def_px calls multileveladp_px
precond_x calls def_px
full_pgcr calls precond_x
full_pgmres calls precond_x
pfgmres calls precond_x
pre_fullgmres calls precond_x, prearnoldi
pre_restartgmres calls precond_x, prearnoldi
prearnoldi calls precond_x
helmholtz_2d calls full_pgcr, full_pgmres, pfgmres, pre_fullgmres, pre_restartgmres