norm – ParaMADP
norm Function
MIT
13 statements
Source File
public function norm(v)
Compute the L2-norm of a complex variable, ONLY for the default grid system.
Arguments
Type Intent Optional Attributes Name
complex(kind=realdp), intent(in), dimension(1-LAP:nx+LAP,1-LAP:ny+LAP) :: v
Return Value real(kind=realdp)
Calls
Called by
Call graph
norm calls mpi_allreduce
arnoldi calls norm
full_pgcr calls norm
full_pgmres calls norm
fullgmres calls norm, arnoldi
pfgmres calls norm
pre_fullgmres calls norm, prearnoldi
pre_restartgmres calls norm, prearnoldi
prearnoldi calls norm
restartgmres calls norm, arnoldi
helmholtz_2d calls full_pgcr, full_pgmres, fullgmres, pfgmres, pre_fullgmres, pre_restartgmres, restartgmres