P_TLKMx – ParaMADP
P_TLKMx Function
MIT
20 statements
Source File
public function P_TLKMx(x, f2c)
Two-Level Krylov Method, P = [(I-M^(-1)AQ)+Q]M^(-1), where Q' is defined based on M^(-1)A M^(-1)x QM^(-1)x
AQM^(-1)x M^(-1)AQM^(-1)x
[(I-M^(-1)AQ)+Q]M^(-1)
Arguments
Type Intent Optional Attributes Name
complex(kind=realdp), intent(inout) :: x(1-LAP:f2c%nxf+LAP,1-LAP:f2c%nyf+LAP)
type(TwoGrids), intent(inout) :: f2c
Return Value complex(kind=realdp), (1-LAP:f2c%nxf+LAP,1-LAP:f2c%nyf+LAP)
Calls
Called by
Call graph
p_tlkmx calls helm_ahx, mgcslp_invmx, qx
helm_ahx calls helmholtz2d_bc_mg
mgcslp_invmx calls f_cycle, finestgrid_define, grid_destroy, v_cycle
qx calls invey, ztx, zx
f_cycle calls f_cycle, grid_destroy, v_cycle, coarsegrid_create, cslp_op_bc, damp_jacobi_smoother, mg_bicgstab, mg_fullgmres, prolongation_en_correct, restriction
helmholtz2d_bc_mg calls helmholtz2d_stencils, if_bcs, mg_check_xy2d
invey calls def_bicgstab, def_fullgmres
v_cycle calls grid_destroy, v_cycle, coarsegrid_create, cslp_op_bc, damp_jacobi_smoother, mg_bicgstab, mg_fullgmres, prolongation_en_correct, restriction
ztx calls mg_check_xy2d
zx calls mg_check_xy2d
cslp_op_bc calls if_bcs, mg_check_xy2d, cslp2d_stencils
damp_jacobi_smoother calls if_bcs, mg_check_xy2d, cslp2d_stencils
def_bicgstab calls coarsegridpara, ex, mg_dot_prod, mg_norm, mgcslp_invmhx
def_fullgmres calls coarsegridpara, def_apply_givens_rotation, def_arnoldi, def_back_substitute, ex, mg_norm, mgcslp_invmhx
if_bcs calls dirichlet, first_order_neum
mg_bicgstab calls cslp_op_bc, mg_dot_prod, mg_norm
mg_check_xy2d calls mg_check_x2d, mg_check_y2d
mg_fullgmres calls cslp_op_bc, mg_apply_givens_rotation, mg_arnoldi, mg_back_substitute, mg_norm
prolongation_en_correct calls mg_check_xy2d
restriction calls mg_check_xy2d, mg_checkreal_xy2d
def_apply_givens_rotation calls cdsqrt
def_arnoldi calls ex, mg_dot_prod, mg_norm, mgcslp_invmhx
ex calls helm_ahx, ztx, zx, coarsegridpara, mgcslp_invmhx, helm_a2hx, ztzx
mg_apply_givens_rotation calls cdsqrt
mg_arnoldi calls cslp_op_bc, mg_dot_prod, mg_norm
mg_check_x2d calls mpi_sendrecv
mg_check_y2d calls mpi_sendrecv
mg_checkreal_xy2d calls mg_checkreal_x2d, mg_checkreal_y2d
mg_dot_prod calls mpi_allreduce
mg_norm calls mpi_allreduce
mgcslp_invmhx calls f_cycle, grid_destroy, v_cycle, gridsys_define
helm_a2hx calls helmholtz2d_bc_mg, helmholtz2d_o4cmpct, helmholtz2d_red_glk
mg_checkreal_x2d calls mpi_sendrecv
mg_checkreal_y2d calls mpi_sendrecv
ztzx calls ztx, zx
helmholtz2d_o4cmpct calls mg_check_xy2d
helmholtz2d_red_glk calls helmholtz2d_stencils, mg_check_xy2d, extrpltghostbcs, red_glk_stencils
def_px calls p_tlkmx
precond_x calls def_px
full_pgcr calls precond_x
full_pgmres calls precond_x
pfgmres calls precond_x
pre_fullgmres calls precond_x, prearnoldi
pre_restartgmres calls precond_x, prearnoldi
prearnoldi calls precond_x
helmholtz_2d calls full_pgcr, full_pgmres, pfgmres, pre_fullgmres, pre_restartgmres