Pre_restartgmres – ParaMADP
Pre_restartgmres Subroutine
MIT
68 statements
Source File
public subroutine Pre_restartgmres(b, u, Rerror, iter)
Preconditioned restart GMRES Be careful!!, after the whole iteration without achieving eps, then the value of j will be "m_iter+1".So we need a k.
Arguments
Type Intent Optional Attributes Name
complex(kind=realdp), intent(in), dimension(1-LAP:nx+LAP,1-LAP:ny+LAP) :: b
complex(kind=realdp), intent(inout), dimension(1-LAP:nx+LAP,1-LAP:ny+LAP) :: u
real(kind=realdp), intent(out) :: Rerror
integer, intent(inout) :: iter
Calls
Called by
Call graph
pre_restartgmres calls apply_givens_rotation, back_substitute, helmholtz2d_bc, norm, prearnoldi, precond_x
apply_givens_rotation calls cdsqrt
helmholtz2d_bc calls check_xy2d, helmholtz2d_stencils, if_bcs
norm calls mpi_allreduce
prearnoldi calls helmholtz2d_bc, norm, precond_x, dot_prod
precond_x calls def_px, mgcslp_invmx
check_xy2d calls check_x2d, check_y2d
def_px calls default_gridpara, multileveladp_px, p_adef1x, p_defx, p_tlkmx
dot_prod calls mpi_allreduce
if_bcs calls dirichlet, first_order_neum
mgcslp_invmx calls f_cycle, finestgrid_define, grid_destroy, v_cycle
check_x2d calls mpi_sendrecv
check_y2d calls mpi_sendrecv
f_cycle calls f_cycle, grid_destroy, v_cycle, coarsegrid_create, cslp_op_bc, damp_jacobi_smoother, mg_bicgstab, mg_fullgmres, prolongation_en_correct, restriction
multileveladp_px calls helm_ax_nth, krylovcslp_invmhx, log2, mgcslp_invmhx, multilevel_invey, ztx, zx
p_adef1x calls mgcslp_invmx, helm_ahx, qx
p_defx calls helm_ahx, qx
p_tlkmx calls mgcslp_invmx, helm_ahx, qx
v_cycle calls grid_destroy, v_cycle, coarsegrid_create, cslp_op_bc, damp_jacobi_smoother, mg_bicgstab, mg_fullgmres, prolongation_en_correct, restriction
cslp_op_bc calls if_bcs, cslp2d_stencils, mg_check_xy2d
damp_jacobi_smoother calls if_bcs, cslp2d_stencils, mg_check_xy2d
helm_ahx calls helmholtz2d_bc_mg
helm_ax_nth calls helmholtz2d_stencils, log2, gridbase_extrpltghostbcs, helm_ax_nth_stencils, mg_check_xy2d
krylovcslp_invmhx calls grid_destroy, gridsys_define, red_glk_cslp_gmres
mg_bicgstab calls cslp_op_bc, mg_dot_prod, mg_norm
mg_fullgmres calls cslp_op_bc, mg_apply_givens_rotation, mg_arnoldi, mg_back_substitute, mg_norm
mgcslp_invmhx calls f_cycle, grid_destroy, v_cycle, gridsys_define
multilevel_invey calls log2, def_prefgmres
prolongation_en_correct calls mg_check_xy2d
qx calls ztx, zx, invey
restriction calls mg_check_xy2d, mg_checkreal_xy2d
ztx calls mg_check_xy2d
zx calls mg_check_xy2d
def_prefgmres calls cdsqrt, multileveladp_px, helm_ax_nth, krylovcslp_invmhx, mg_dot_prod, mg_norm, coarsegridpara
helm_ax_nth_stencils calls log2
helmholtz2d_bc_mg calls helmholtz2d_stencils, if_bcs, mg_check_xy2d
invey calls def_bicgstab, def_fullgmres
mg_apply_givens_rotation calls cdsqrt
mg_arnoldi calls cslp_op_bc, mg_dot_prod, mg_norm
mg_check_xy2d calls mg_check_x2d, mg_check_y2d
mg_checkreal_xy2d calls mg_checkreal_x2d, mg_checkreal_y2d
mg_dot_prod calls mpi_allreduce
mg_norm calls mpi_allreduce
red_glk_cslp_gmres calls cdsqrt, log2, mg_dot_prod, mg_norm, cslp_mx_nth
cslp_mx_nth calls log2, cslp2d_stencils, gridbase_extrpltghostbcs, mg_check_xy2d, cslp_mx_nth_stencils
def_bicgstab calls mgcslp_invmhx, mg_dot_prod, mg_norm, coarsegridpara, ex
def_fullgmres calls mgcslp_invmhx, mg_norm, coarsegridpara, def_apply_givens_rotation, def_arnoldi, def_back_substitute, ex
mg_check_x2d calls mpi_sendrecv
mg_check_y2d calls mpi_sendrecv
mg_checkreal_x2d calls mpi_sendrecv
mg_checkreal_y2d calls mpi_sendrecv
cslp_mx_nth_stencils calls log2
def_apply_givens_rotation calls cdsqrt
def_arnoldi calls mgcslp_invmhx, mg_dot_prod, mg_norm, ex
ex calls helm_ahx, mgcslp_invmhx, ztx, zx, coarsegridpara, helm_a2hx, ztzx
helm_a2hx calls helmholtz2d_bc_mg, helmholtz2d_o4cmpct, helmholtz2d_red_glk
ztzx calls ztx, zx
helmholtz2d_o4cmpct calls mg_check_xy2d
helmholtz2d_red_glk calls helmholtz2d_stencils, mg_check_xy2d, extrpltghostbcs, red_glk_stencils
helmholtz_2d calls pre_restartgmres