read_wavenumber_k_marmousi – ParaMADP
read_wavenumber_k_marmousi Subroutine
MIT
62 statements
Source File
public subroutine read_wavenumber_k_marmousi()
Read the velocity profile of Marmousi problem with specified grid size and calculate the wavenumber
Arguments
None
Calls
Called by
Call graph
read_wavenumber_k_marmousi calls mpi_recv, mpi_send, mg_checkreal_xy2d
mg_checkreal_xy2d calls mg_checkreal_x2d, mg_checkreal_y2d
mg_checkreal_x2d calls mpi_sendrecv
mg_checkreal_y2d calls mpi_sendrecv
helmholtz_2d calls read_wavenumber_k_marmousi