ReD_Glk_CSLP_bicgstab – ParaMADP
ReD_Glk_CSLP_bicgstab Subroutine
MIT
80 statements
Source File
public subroutine ReD_Glk_CSLP_bicgstab(mg_solve, grid, maximum_iterations)
This is a rountine to solve a coarse grid CSLP system approximately by using Bi-CGSTAB. The CSLP operator is defined by ReD-Glk scheme. CSLP operator by ReD-Glk
Arguments
Type Intent Optional Attributes Name
type(GridSystem), intent(inout) :: mg_solve
The current coarse grid system
type(Gridpara) :: grid
Parameters of current coarse grid
integer, intent(in), optional :: maximum_iterations
Calls
Call graph
red_glk_cslp_bicgstab calls cslp_mx_nth, mg_dot_prod, mg_norm
cslp_mx_nth calls cslp2d_stencils, cslp_mx_nth_stencils, gridbase_extrpltghostbcs, log2, mg_check_xy2d
mg_dot_prod calls mpi_allreduce
mg_norm calls mpi_allreduce
cslp_mx_nth_stencils calls log2
mg_check_xy2d calls mg_check_x2d, mg_check_y2d
mg_check_x2d calls mpi_sendrecv
mg_check_y2d calls mpi_sendrecv