restartgmres – ParaMADP
restartgmres Subroutine
MIT
61 statements
Source File
public subroutine restartgmres(b, u, Rerror, iter_total)
Restart GMRES Be careful!!, after the whole iteration without achieving eps, then the value of j will be "m_iter+1".So we need a k.
Arguments
Type Intent Optional Attributes Name
complex(kind=realdp), intent(in), dimension(1-LAP:nx+LAP,1-LAP:ny+LAP) :: b
complex(kind=realdp), intent(inout), dimension(1-LAP:nx+LAP,1-LAP:ny+LAP) :: u
real(kind=realdp), intent(out) :: Rerror
integer, intent(inout) :: iter_total
Calls
Called by
Call graph
restartgmres calls apply_givens_rotation, arnoldi, back_substitute, helmholtz2d_bc, norm
apply_givens_rotation calls cdsqrt
arnoldi calls helmholtz2d_bc, norm, dot_prod
helmholtz2d_bc calls check_xy2d, helmholtz2d_stencils, if_bcs
norm calls mpi_allreduce
check_xy2d calls check_x2d, check_y2d
dot_prod calls mpi_allreduce
if_bcs calls dirichlet, first_order_neum
check_x2d calls mpi_sendrecv
check_y2d calls mpi_sendrecv
helmholtz_2d calls restartgmres