OPERATOR(*) – ParaMADP
OPERATOR(*) Interface
MIT
3 statements
Source File
public interface OPERATOR(*)
Calls
Module Procedures
public function rmatvec(A, v)
This is an empty matrix-vector multiplication for real-type input v
Arguments
Type Intent Optional Attributes Name
type(matrix), intent(in) :: A
real(kind=realdp), intent(in) :: v(:,:)
Return Value real(kind=realdp), (size(v,1),size(v,2))
public function cmatvec(A, v)
This is complex matrix-vector multiplication
Arguments
Type Intent Optional Attributes Name
type(matrix), intent(in) :: A
complex(kind=realdp), intent(in) :: v(:,:)
Return Value complex(kind=realdp), (size(v,1),size(v,2))
Call graph
operator(ASTERISK) calls cmatvec, rmatvec
cmatvec calls helmholtz2d_bc
helmholtz2d_bc calls check_xy2d, helmholtz2d_stencils, if_bcs
check_xy2d calls check_x2d, check_y2d
if_bcs calls dirichlet, first_order_neum
check_x2d calls mpi_sendrecv
check_y2d calls mpi_sendrecv