OPERATOR(/) – ParaMADP
OPERATOR(/) Interface
MIT
3 statements
Source File
public interface OPERATOR(/)
Calls
Module Procedures
public function rprecon(v, M1)
This is an empty preconditioner for real-type input v
Arguments
Type Intent Optional Attributes Name
real(kind=realdp), intent(in), dimension(:,:) :: v
type(preconditioner), intent(in) :: M1
Return Value real(kind=realdp), dimension(size(v,1),size(v,2))
public function cprecon(v, M1)
This is an preconditioner for complex-type input v, i.e. M1^(-1)v We can manully call different preconditioners here. Here only use multigrid-based CLSP
Arguments
Type Intent Optional Attributes Name
complex(kind=realdp), intent(in) :: v(:,:)
type(preconditioner), intent(in) :: M1
Return Value complex(kind=realdp), (size(v,1),size(v,2))
Call graph
operator(SLASH) calls cprecon, rprecon
cprecon calls mgcslp_invmx
mgcslp_invmx calls f_cycle, finestgrid_define, grid_destroy, v_cycle
f_cycle calls f_cycle, grid_destroy, v_cycle, coarsegrid_create, cslp_op_bc, damp_jacobi_smoother, mg_bicgstab, mg_fullgmres, prolongation_en_correct, restriction
v_cycle calls grid_destroy, v_cycle, coarsegrid_create, cslp_op_bc, damp_jacobi_smoother, mg_bicgstab, mg_fullgmres, prolongation_en_correct, restriction
cslp_op_bc calls cslp2d_stencils, if_bcs, mg_check_xy2d
damp_jacobi_smoother calls cslp2d_stencils, if_bcs, mg_check_xy2d
mg_bicgstab calls cslp_op_bc, mg_dot_prod, mg_norm
mg_fullgmres calls cslp_op_bc, mg_apply_givens_rotation, mg_arnoldi, mg_back_substitute, mg_norm
prolongation_en_correct calls mg_check_xy2d
restriction calls mg_check_xy2d, mg_checkreal_xy2d
if_bcs calls dirichlet, first_order_neum
mg_apply_givens_rotation calls cdsqrt
mg_arnoldi calls cslp_op_bc, mg_dot_prod, mg_norm
mg_check_xy2d calls mg_check_x2d, mg_check_y2d
mg_checkreal_xy2d calls mg_checkreal_x2d, mg_checkreal_y2d
mg_dot_prod calls mpi_allreduce
mg_norm calls mpi_allreduce
mg_check_x2d calls mpi_sendrecv
mg_check_y2d calls mpi_sendrecv
mg_checkreal_x2d calls mpi_sendrecv
mg_checkreal_y2d calls mpi_sendrecv