TwoGrids – ParaMADP
TwoGrids Interface
MIT
3 statements
Source File
public interface TwoGrids
Calls
Module Procedures
public function FromFine2Coarse(OneGrid)
A procedure to create a two-grid system from a given fine Gridpara type The wavenumber of the coarse level is restricted from the fine level
Arguments
Type Intent Optional Attributes Name
type(Gridpara), intent(inout) :: OneGrid
Return Value type(TwoGrids)
Call graph
twogrids calls fromfine2coarse
fromfine2coarse calls wavenumber_fwrestriction
wavenumber_fwrestriction calls mg_checkreal_xy2d
mg_checkreal_xy2d calls mg_checkreal_x2d, mg_checkreal_y2d
mg_checkreal_x2d calls mpi_sendrecv
mg_checkreal_y2d calls mpi_sendrecv