helmholtz_2d – ParaMADP
helmholtz_2d Program
MIT
192 statements
Source File
Uses
user_module
define_grid
read_setup
analytical_sol
solvers
write_data
comm_variable
mpi
define_rhs
mpi_setup
idrs_module
wavenumber
Parallel proconditioned Krylov slover for 2D Helmholtz equation
Calls
Variables
Type Attributes Name Initial
type(matrix) :: A
An empty matrix type for calling idrs solver
type(preconditioner) :: M1
a preconditioner type for calling idrs solver. Since the IDR(s) solver part is ported, its input and output parameters are somewhat different from other solvers.
complex(kind=realdp), allocatable, dimension(:,:) :: u
arrays for the solution
complex(kind=realdp), allocatable, dimension(:,:) :: u_ex
arrays for exact solution
complex(kind=realdp), allocatable, dimension(:,:) :: u_err
arrays for the error of solution
complex(kind=realdp), allocatable, dimension(:,:) :: b
arrays for the right-hand side
real(kind=realdp), allocatable, dimension(:,:) :: xx
coordinates
real(kind=realdp), allocatable, dimension(:,:) :: yy
coordinates
real(kind=realdp), allocatable :: resvec(:)
Residual vector for idrs solver
real(kind=realdp) :: time_start
time_start: variable for runtime measurement start
real(kind=realdp) :: time_end
time_end: variable for runtime measurement end
real(kind=realdp) :: u_err_max
u_err_max: local max|u_err|=max|u-u_ex|
real(kind=realdp) :: Aerror
Aerror: global max|u_err|=max|u-u_ex|
real(kind=realdp) :: Rerror
Rerror: relative residual ||b-Au||/||b||
real(kind=realdp) :: max_k_local
max_k_local: local maximum wavenumber
real(kind=realdp) :: max_k_global
max_k_global: global maximum wavenumber
integer :: iter
number of iterations and loop indexs
integer :: k
number of iterations and loop indexs
integer :: i
number of iterations and loop indexs
integer :: j
number of iterations and loop indexs
integer :: flag
an output flag for idrs solvers
Call graph
helmholtz_2d calls idrs, mpi_allreduce, mpi_barrier, mpi_comm_rank, mpi_comm_size, mpi_finalize, mpi_init, mpi_reduce, mpi_wtime, const_k, define_marmousi_grid, define_uniform_grid, define_wedge_grid, exact_2dcloseoff, exact_2dpointsource_1stsomer, exact_2dpointsource_dirichlet, full_pgcr, full_pgmres, fullgmres, log2, part2d, pfgmres, pre_fullgmres, pre_restartgmres, read_parameter, read_wavenumber_k_marmousi, restartgmres, rhs_2dcloseoff, rhs_2dwedge, rhs_centersource2d, rhs_marmousi, wavenumber_k_destroy, wavenumber_k_wedge, write_data_whole
const_k calls mg_checkreal_xy2d
define_marmousi_grid calls mpi_recv, mpi_send
define_uniform_grid calls mpi_recv, mpi_send
define_wedge_grid calls mpi_recv, mpi_send
exact_2dcloseoff calls dsin
full_pgcr calls dot_prod, helmholtz2d_bc, norm, precond_x
full_pgmres calls apply_givens_rotation, back_substitute, dot_prod, helmholtz2d_bc, norm, precond_x
fullgmres calls apply_givens_rotation, arnoldi, back_substitute, helmholtz2d_bc, norm
part2d calls mpi_barrier, my_mod1
pfgmres calls apply_givens_rotation, back_substitute, dot_prod, helmholtz2d_bc, norm, precond_x
pre_fullgmres calls apply_givens_rotation, back_substitute, helmholtz2d_bc, norm, prearnoldi, precond_x
pre_restartgmres calls apply_givens_rotation, back_substitute, helmholtz2d_bc, norm, prearnoldi, precond_x
read_parameter calls mpi_barrier, mpi_bcast
read_wavenumber_k_marmousi calls mpi_recv, mpi_send, mg_checkreal_xy2d
restartgmres calls apply_givens_rotation, arnoldi, back_substitute, helmholtz2d_bc, norm
wavenumber_k_wedge calls mg_checkreal_xy2d
write_data_whole calls mpi_recv, mpi_send
apply_givens_rotation calls cdsqrt
arnoldi calls dot_prod, helmholtz2d_bc, norm
dot_prod calls mpi_allreduce
helmholtz2d_bc calls check_xy2d, helmholtz2d_stencils, if_bcs
mg_checkreal_xy2d calls mg_checkreal_x2d, mg_checkreal_y2d
norm calls mpi_allreduce
prearnoldi calls dot_prod, helmholtz2d_bc, norm, precond_x
precond_x calls def_px, mgcslp_invmx
check_xy2d calls check_x2d, check_y2d
def_px calls default_gridpara, multileveladp_px, p_adef1x, p_defx, p_tlkmx
if_bcs calls dirichlet, first_order_neum
mg_checkreal_x2d calls mpi_sendrecv
mg_checkreal_y2d calls mpi_sendrecv
mgcslp_invmx calls f_cycle, finestgrid_define, grid_destroy, v_cycle
check_x2d calls mpi_sendrecv
check_y2d calls mpi_sendrecv
f_cycle calls f_cycle, grid_destroy, v_cycle, coarsegrid_create, cslp_op_bc, damp_jacobi_smoother, mg_bicgstab, mg_fullgmres, prolongation_en_correct, restriction
multileveladp_px calls log2, helm_ax_nth, krylovcslp_invmhx, mgcslp_invmhx, multilevel_invey, ztx, zx
p_adef1x calls mgcslp_invmx, helm_ahx, qx
p_defx calls helm_ahx, qx
p_tlkmx calls mgcslp_invmx, helm_ahx, qx
v_cycle calls grid_destroy, v_cycle, coarsegrid_create, cslp_op_bc, damp_jacobi_smoother, mg_bicgstab, mg_fullgmres, prolongation_en_correct, restriction
cslp_op_bc calls if_bcs, cslp2d_stencils, mg_check_xy2d
damp_jacobi_smoother calls if_bcs, cslp2d_stencils, mg_check_xy2d
helm_ahx calls helmholtz2d_bc_mg
helm_ax_nth calls log2, helmholtz2d_stencils, gridbase_extrpltghostbcs, helm_ax_nth_stencils, mg_check_xy2d
krylovcslp_invmhx calls grid_destroy, gridsys_define, red_glk_cslp_gmres
mg_bicgstab calls cslp_op_bc, mg_dot_prod, mg_norm
mg_fullgmres calls cslp_op_bc, mg_apply_givens_rotation, mg_arnoldi, mg_back_substitute, mg_norm
mgcslp_invmhx calls f_cycle, grid_destroy, v_cycle, gridsys_define
multilevel_invey calls log2, def_prefgmres
prolongation_en_correct calls mg_check_xy2d
qx calls ztx, zx, invey
restriction calls mg_checkreal_xy2d, mg_check_xy2d
ztx calls mg_check_xy2d
zx calls mg_check_xy2d
def_prefgmres calls cdsqrt, multileveladp_px, helm_ax_nth, krylovcslp_invmhx, mg_dot_prod, mg_norm, coarsegridpara
helm_ax_nth_stencils calls log2
helmholtz2d_bc_mg calls helmholtz2d_stencils, if_bcs, mg_check_xy2d
invey calls def_bicgstab, def_fullgmres
mg_apply_givens_rotation calls cdsqrt
mg_arnoldi calls cslp_op_bc, mg_dot_prod, mg_norm
mg_check_xy2d calls mg_check_x2d, mg_check_y2d
mg_dot_prod calls mpi_allreduce
mg_norm calls mpi_allreduce
red_glk_cslp_gmres calls log2, cdsqrt, mg_dot_prod, mg_norm, cslp_mx_nth
cslp_mx_nth calls log2, cslp2d_stencils, gridbase_extrpltghostbcs, mg_check_xy2d, cslp_mx_nth_stencils
def_bicgstab calls mgcslp_invmhx, mg_dot_prod, mg_norm, coarsegridpara, ex
def_fullgmres calls mgcslp_invmhx, mg_norm, coarsegridpara, def_apply_givens_rotation, def_arnoldi, def_back_substitute, ex
mg_check_x2d calls mpi_sendrecv
mg_check_y2d calls mpi_sendrecv
cslp_mx_nth_stencils calls log2
def_apply_givens_rotation calls cdsqrt
def_arnoldi calls mgcslp_invmhx, mg_dot_prod, mg_norm, ex
ex calls helm_ahx, mgcslp_invmhx, ztx, zx, coarsegridpara, helm_a2hx, ztzx
helm_a2hx calls helmholtz2d_bc_mg, helmholtz2d_o4cmpct, helmholtz2d_red_glk
ztzx calls ztx, zx
helmholtz2d_o4cmpct calls mg_check_xy2d
helmholtz2d_red_glk calls helmholtz2d_stencils, mg_check_xy2d, extrpltghostbcs, red_glk_stencils